	.xlist
;
;------------------------------------------------------------------------------
;
; Conditional assembly switch
;
HYBRID	equ	-1		;DOS1/DOS2 hybrid system
STURBO	equ	-1		;support super turbo mode (for MSXturboR)
BUILTIN	equ	-1		;built-in system

ALPHA	equ	0		;Level of Alpha release (0: no alpha)
BETA	equ	0		;Level of Beta release (0: no beta)
RC	equ	0		;Level of RC (0: no RC)
;
;-----------------------------------------------------------------------------
;
	.list
;
