	.xlist
;
;------------------------------------------------------------------------------
	
ALPHA	equ	2		;Level of Alpha release (0: no alpha)
ALPHAL	equ	""		;Letter after the Alpha release number, or empty
BETA	equ	0		;Level of Beta release (0: no beta)
RC	equ	0		;Level of RC (0: no RC)
RR	equ	0       ;Level of release (0: no release level)
;
;-----------------------------------------------------------------------------
;
	.list
;
