	.xlist
;
;------------------------------------------------------------------------------
;
; Conditional assembly switch
;
HYBRID	equ	-1		;DOS1/DOS2 hybrid system
STURBO	equ	-1		;support super turbo mode (for MSXturboR)
BUILTIN	equ	-1		;built-in system

ALPHA	equ	0		;Level of Alpha release (0: no alpha)
ALPHAL	equ	""		;Letter after the Alpha release number, or empty
BETA	equ	2		;Level of Beta release (0: no beta)
RC	equ	0		;Level of RC (0: no RC)
RR  equ 0       ;Level of release (0: no release level)
;
;-----------------------------------------------------------------------------
;
	.list
;
