;------------------------------------------------------------------------------
;
; Nextor KERNEL version numbers and prerelease levels.
;
;------------------------------------------------------------------------------

MAIN_NEXTOR_VERSION	equ	3
SEC_NEXTOR_VERSION_HIGH	equ	0
SEC_NEXTOR_VERSION_LOW	equ	0

; Pre-release level (0 = none; normally at most one is non-zero)
ALPHA	equ	0		;Level of Alpha release (0: no alpha)
BETA	equ	1		;Level of Beta release (0: no beta)
RC	equ	0		;Level of RC (0: no RC)
RR	equ	0		;Level of release (0: no release level)
