	TITLE	MSX-DOS 2 - COMMAND2.COM
	SUBTTL	Non-disk commands
;******************************************************************************
;
;        The internal commands that do not deal with files: batch flow
; control (GOTO/GOSUB/RETURN/END), IF and IFF/THEN/ELSE/ENDIFF, screen and
; keyboard commands, environment and alias management, HISTORY, MEMORY,
; date and time.
;
;        Based on COMMAND.COM 2.31, copyright (1986) IS Systems Ltd, and on
; the COMMAND2.COM 2.40/2.41 additions by Fokke Post, whose source code was
; released as freeware in 2003.
;
;******************************************************************************
@REM:	XOR	A
	RET

@BEEP:	AND	(HL)
	LD	A,.INP
	RET	NZ
	LD	A,#07
	JP	PRCHAR

;        This module contains the command routines for the  assorted  commands
; which are not directly related to the disk system eg. CLS and DATE.
		SUBTTL	ASSIGN
;        This  is  the  ASSIGN  command  routine,  which  either  sets  up  an
; assignment,  clears all assignments or displays the current assignment for a
; specified drive. Note that a drive can be un-assigned without affecting  the
; other drives by assigning it to itself.
@ASSIGN:	AND	(HL)	; If no parameters, then just cancel
	LD	B,A	;   all assigns.
	LD	D,A
	LD	C,_ASSIGN
	JP	Z,BDOS

	CALL	PARSDR	; Parse a drive letter.
	RET	NZ
	LD	B,D	; Save in B.
	CALL	GETCH
	JR	NZ,ASN10	; Go if second drive given.
	LD	D,#FF	; Else get current assign for this
	LD	C,_ASSIGN	;   drive.
	PUSH	BC
	CALL	BDOS
	POP	BC
	RET	NZ
	LD	HL,LPRINT	; Print CRLF at end.
	PUSH	HL
	CALL	DDRV	; Print drive.
	LD	A,"="	; Print '=' and the other drive.
	CALL	PRCHAR
	LD	B,D
DDRV:	LD	A,B
	ADD	A,"@"
	CALL	PRCHAR	; Print drive letter.
	LD	A,":"
	JP	PRCHAR

ASN10:	CALL	PARSDR	; Get second drive.
	RET	NZ
	CALL	GETCH	; Make sure there's no garbage on the
	LD	A,.INP	;   end of the line.
	RET	NZ
	LD	C,_ASSIGN	; Attempt to set up new assign.
	JP	BDOS

PARSDR:	LD	A,(HL)	; Get drive letter.
	CALL	UC
	SUB	"@"	; Attempt to convert to drive number.
	JR	C,IDRV	; Invalid drive if < 'A'.
	JR	Z,IDRV
	CP	#1B	; Invalid drive if > 'Z'.
	JR	NC,IDRV
	LD	D,A	; Return drive in D.
	INC	HL
	LD	A,(HL)	; Allow a colon afterwards.
	CP	":"
	JR	NZ,NCOL
	INC	HL
NCOL:	LD	A,(HL)	; Make sure drive is followed by a
	CALL	SEP?	;   separator character.
	RET	Z	; OK if it is.
IDRV:	LD	A,.IDRV
	OR	A
	RET

@BASIC:	CALL	LDCOME
	RET	NZ
	LD	HL,VAREND	; Release variable memory
	LD	A,#FF
	CALL	WRCHR
	INC	HL
	LD	A,#BF
	CALL	WRCHR
	LD	SP,#F51F
	CALL	#F368
	JP	#4022

@BUFFERS:	AND	(HL)
	JR	NZ,SETBUF
	LD	BC,_BUFFER
	CALL	BDOS
	RET	NZ
	PUSH	BC
	LD	A,#27
	CALL	DMESS
	POP	AF
	LD	IX,ENVDATA
	PUSH	IX
	CALL	D8
	POP	DE
	JP	DMSCR

SETBUF:	CALL	GET8	; Get the number specified into E.
	CALL	Z,CHKNO
	RET	NZ
	LD	A,(HL)	; Check for garbage on the end of the
	OR	A	;   line.
	LD	A,.INP
	RET	NZ	; Give error if too many parameters.
	LD	B,E	; Get specified number.
	LD	C,_BUFFER
	JP	BDOS	; Attempt to set that number.

@CLS:	AND	(HL)
	LD	A,.INP
	RET	NZ
	LD	A,#0C
	JP	PRCHAR

@CPU:	AND	(HL)
	JR	Z,CAL20
	LD	A,(HL)
	INC	HL
	SUB	"0"
	JR	C,CAL10
	CP	3
	JR	NC,CAL10
	EX	AF,AF'
	CALL	GETCH
	LD	A,.INP
	RET	NZ
	LD	A,(MSXVER)
	CP	3
	LD	A,0
	RET	C
	EX	AF,AF'
	OR	%10000000
	LD	IX,#0180

CALLSLOT:	LD	IY,(EXPTBL-1)
	LD	HL,#00
	ADD	HL,SP
	LD	SP,#F51F
	PUSH	HL
	CALL	CALSLT
	POP	HL
	LD	SP,HL
	LD	E,A
	XOR	A
	LD	IY,REDIRST
	RET

CAL10:	LD	A,.BADNO
	OR	A
	RET

CAL20:	LD	A,#43
	CALL	DMESS
	LD	A,(MSXVER)
	CP	3
	LD	A,#44
	JP	C,DMESSCR
	LD	IX,#0183
	CALL	CALLSLOT
	LD	A,E
	ADD	A,#44
	JP	DMESSCR

@DATE:	PUSH	HL
	CALL	DFORM
	POP	HL
	LD	A,(HL)
	OR	A
	JR	NZ,RDAT
	LD	C,_GDATE
	CALL	BDOS
	PUSH	HL
	PUSH	DE
	PUSH	AF
	LD	A,#16
	CALL	DMESS
	POP	AF
	ADD	A,#17
	CALL	DMESS
	LD	A,#1E
	CALL	DMESS
	POP	DE
	POP	HL
	LD	BC,#F844
	ADD	HL,BC
	LD	A,D
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	RL	L
	OR	E
	LD	D,L
	LD	HL,ENVNAME+1
	LD	(HL),D
	DEC	HL
	LD	(HL),A
	LD	C,#FF
	LD	IX,ENVNAME+2
	PUSH	IX
	CALL	DDATE
	POP	DE
	CALL	PRTSTR
	LD	A,#1F
	CALL	DMESSCR
NEWDAT:	LD	A,#20	; Print 'Enter new date'.
	CALL	DMESS
	LD	HL,DATE$	; Get the DATE environment string.
	CALL	GENV2
	JR	NZ,NDFORM	; Don't print the format if error.
	LD	A,(DE)	; DATE in the environment ?
	OR	A
	JR	Z,NDFORM	; Go if not.
	PUSH	DE
	LD	A,#22	; Else print the format from the
	CALL	DMESS	;   environment.
	POP	DE
	CALL	PRTSTR
	LD	A,#23
	CALL	DMESS
NDFORM:	LD	A,#21	; Print end message.
	CALL	DMESS
	CALL	INLI	; Input a line.
	JR	Z,DAT5	; Go if no error.
	CP	.EOF
	RET	NZ	; Return if not end of file error.
DAT5:	INC	HL	; Point passed length byte.
	CALL	GETCH	; Skip leading separators.
	RET	Z	; Just return if new date not given.
RDAT:	EXX	; Hide the input line pointer.
	LD	C,_GDATE	; Get current date again for defaults.
	CALL	BDOS
	EXX	; Save current values, get input ptr.
	LD	A,(IY+#12)
	ADD	A,A	; Ignore top two bits.
	ADD	A,A
	LD	B,#03	; Read 3 numbers.
	PUSH	AF	; Save format variable.
	JR	DAT20

DAT10:	CALL	DTSKIP	; Skip date/time separators.
	JR	C,BADAT	; Go if invalid.
DAT20:	CALL	GETNO	; Get a number.
	EXX
	LD	B,A	; Save number.
	SBC	A,A	; FF => invalid number, 0 => OK.
	LD	C,A	; Save error flag.
	POP	AF	; Get & adjust format variable for this
	RLCA	;   iteration.
	RLCA
	PUSH	AF
	INC	C	; Error ?
	JR	Z,DAT50	; Use default value if yes.
	AND	#03	; Mask out other grotty bits.
	JR	Z,DAT50	; Go if invalid field value.
	DEC	A	; Day ?
	JR	Z,DAT40	; Go if yes.
	DEC	A	; Month ?
	JR	Z,DAT30	; Go if yes, else year.
	EXX
	CALL	GETDIG	; See if more digits of the number.
	JR	C,NOCENT	; Go if not (century not given).
	INC	HL	; Point to next digit.
	CALL	GNO	; Get second digit.
	JR	C,BADAT	; Error if invalid.
	EXX
	SUB	#50	; Convert 80-99 to offset from 1980.
	LD	C,A	; Save year part.
	LD	A,B	; Get century.
	CP	#13
	JR	Z,ADD1980	; Go if 19xx with offset from 1980.
	CP	#14
	LD	A,C	; Get year.
	JR	Z,CENT20	; Go if 20xx.
BADAT:	POP	AF	; Balance stack.
	LD	B,.IDATE	; Give 'Invalid date' error.
	JR	DAT60	; Print error, re-prompt.

NOCENT:	EXX
	LD	A,B	; Get given year.
	SUB	#50	; 80-99 -> 0-19 (offset from 1980).
	JR	NC,CENT19	; Go if 1980-1999.
CENT20:	ADD	A,#64	; Convert to offset into 2000..
CENT19:	LD	C,A
ADD1980:	LD	B,#00	; BC=offset from 1980.
	LD	HL,#07BC
	ADD	HL,BC	; HL=new date.
	LD	B,D	; Skip to DAT50.
DAT30:	LD	D,B	; Save month.
	DEFB	#06
DAT40:	LD	E,B
DAT50:	EXX	; Save new date, get line ptr.
	DJNZ	DAT10	; Get separator & next digit.
	CALL	GETCH	; Skip trailing spaces.
	JR	NZ,BADAT	; Error if end of line.
	POP	AF	; Balance stack.
	EXX	; Get the new date.
	LD	C,_SDATE
	CALL	BDOS	; Attempt to set the new date.
	AND	.IDATE	; .IDATE if error, else 0.
	RET	Z	; Return if no error.
	LD	B,A
DAT60:	LD	DE,ENVNAME
	LD	C,_EXPLAIN
	CALL	BDOS
	PUSH	DE
	CALL	LPRINT
	LD	A,#0D
	CALL	DMESS
	POP	DE
	CALL	PRTSTR
	LD	A,#0E
	CALL	DMESSCR
	JP	NEWDAT

		SUBTTL	ECHO
;        The ECHO command just prints it's arguments on the screen. It is used
; for displaying comments ans messages in batch files.
;
;        ECHOS (new in 2.40) does the same, but without the trailing CR/LF.
;
@ECHO:	EX	DE,HL	; DE -> arguments.
	JP	DMSCR	; Print rest of command line & CR,LF.

@ECHOS:	EX	DE,HL	; DE -> arguments.
	JP	PRTSTR	; Print rest of command line only.

		SUBTTL	EXIT
;        The EXIT command reads an optional error number as it's argument  and
; then  exits  this invokation of COMMAND with the error code. It restores the
; pointers at the bottom of page 0, the BIOS re-boot jump entry point and  the
; environment strings which COMMAND saved when it was first entered.
@EXIT:	AND	(HL)
	JR	Z,EXIT	; EXIT with no error if no parameters.
	CALL	GET8	; Else read a number into E.
	CALL	Z,CHKNO	; Check for garbage after number.
	CALL	Z,CHKEOL	; Check for garbage on end of line.
	RET	NZ
	LD	A,E

EXIT:	PUSH	AF	; Save error code for returning.
	LD	HL,BOOTSTRAP	; Restore vectors in page 0 to what
	LD	DE,#00	;   they were when COMMAND was invoked.
	LD	BC,#08
	LDIR
	CP	.OKCMD	; Restore environment strings unless
	JR	Z,ENVDON	;   end of COMMAND <command> (eg.
;					;   AUTOEXEC.BAT).
	LD	DE,#01	; Delete first environment string.
DELENV:	PUSH	DE
	CALL	FENV	; Get name of item.
	POP	DE
	INC	DE
	JR	NZ,DELENV	; Do next if error.
	OR	(HL)	; Name null (end of strings) ?
	JR	Z,SETENV	; All deleted if yes.
	PUSH	DE
	LD	DE,ENVDATA
	XOR	A
	LD	(DE),A	; Set to a null string to delete.
	LD	C,_SENV	; Else set item to null.
	CALL	BDOS
	POP	DE	; Now the 1st string's deleted, the 2nd
	DEC	DE	;   string's become the new first
	JR	DELENV	;   string so DE not incremented.

SETENV:	LD	HL,(#06)	; Find out address of saved environment
	DEC	HL	;   strings, and restore them.
	DEC	HL
	DEC	HL
	DEC	HL
	DEC	HL
	DEC	HL
	DEC	HL
CPYENV:	LD	A,(HL)	; End of environment string list ?
	OR	A
	JR	Z,ENVDON
	LD	DE,ENVNAME	; Copy name of item to BUFF2.
CPY20:	LD	A,(HL)	; Get character.
	LD	(DE),A
	DEC	HL
	INC	DE
	OR	A
	JR	NZ,CPY20	; Copy until null at end.
	LD	DE,ENVDATA	; Copy saved value of item to BUFF.
CPY30:	LD	A,(HL)
	LD	(DE),A
	DEC	HL
	INC	DE
	OR	A
	JR	NZ,CPY30	; Copy until null at end.
	PUSH	HL
	CALL	SENV	; Set value.
	POP	HL	; HL -> next string.
	JR	CPYENV

ENVDON:	LD	HL,(#01)
	INC	HL
	LD	DE,(WARMBOOT)	; Restore re-boot BIOS jump
	LD	(HL),E	;   table entry point.
	INC	HL
	LD	(HL),D
	LD	DE,#00	; Un-define abort routine.
	LD	C,_DEFAB
	CALL	BDOS	;   (error ignored)
	POP	BC	; Restore error code in B.
	LD	C,_TERM
	JP	BDOS	; Terminate with error code.

		SUBTTL	FORMAT
;        This is the FORMAT command routine. It simply takes an optional drive
; letter and passes this to the format BDOS function.
@FORMAT:	AND	(HL)
	LD	B,A	; Use default drive if none specified.
	JR	NZ,FMT_HAS_ARG	;
	LD	L,#00
	LD	BC,#0867
FMT_CHK_DRIVE:	ADD	HL,HL
	PUSH	HL
	PUSH	BC
	XOR	A	;See if format is supported by
	CALL	BDOS	; drive [B].
	POP	BC
	POP	HL
	JR	NZ,FMT_NO_DRIVE	;Any error means drive does not exist
	INC	HL	;Add to the selection list.
FMT_NO_DRIVE:	DJNZ	FMT_CHK_DRIVE
	LD	A,L	;If nothing remains, no way to proceed.
	OR	A	;
	LD	A,.IDRV	;
	RET	Z	;
	LD	A,L
	DEC	A
	AND	L
	LD	A,L	;If only one drive,
	JR	Z,FMT_1DRIVE	; no need to ask for drive name
	PUSH	HL	;Save drive list.
	LD	A,#2A
	CALL	DMESS	;"Drive name? (".
	POP	HL
	PUSH	HL
	LD	A,"@"
FMT_ASK_LOOP:	INC	A
	SRL	L
	JR	NC,FMT_SKIPDRV
	PUSH	AF
	CALL	PRCHAR	;Print drive name.
	POP	AF
	PUSH	AF
	LD	A,","
	CALL	NZ,PRCHAR	;Print separator if something remain.
	POP	AF
FMT_SKIPDRV:	JR	NZ,FMT_ASK_LOOP
	LD	A,#2B
	CALL	DMESS	;") " after drive name list.
	POP	HL	;Restore drive list
FMT_ASKAGAIN:	PUSH	HL
	LD	C,_CONST	; Get a character, gobbling up chars
	CALL	BDOS	;   in the keyboard buffer.
	PUSH	AF
	LD	C,_INNOE
	CALL	BDOS
	LD	C,A
	POP	AF
	POP	HL
	JR	NZ,FMT_ASKAGAIN
	LD	A,C
	CALL	UC	;Force to upper case
	LD	C,A
	SUB	"A"
	CP	#08
	JR	NC,FMT_ASKAGAIN	;Invalid drive name.
	LD	B,A
	INC	B
	XOR	A
	SCF
FMT_GETMASK:	RLA
	DJNZ	FMT_GETMASK
	AND	L
	JR	Z,FMT_ASKAGAIN	;Drive does not exist
					; or does not support format.
	PUSH	AF
	LD	A,C
	CALL	PRCHAR	;Echo to the console.
	CALL	LPRINT
	POP	AF
FMT_1DRIVE:	INC	B	;Always comes here with B=0.
	RRCA	;
	JR	NC,FMT_1DRIVE
	JR	NFDRV

FMT_HAS_ARG:	INC	HL
	LD	A,(HL)
	CP	":"
	LD	A,.IPARM
	RET	NZ
	INC	HL
	LD	A,(HL)
	CALL	SEP?
	LD	A,.IPARM
	RET	NZ
	LD	A,B
	CALL	UC
	CP	"Z"+1
	JR	NC,NCIDRV
	SUB	"A"
	LD	B,A
	CCF
NCIDRV:	LD	A,.IDRV
	RET	NC
	INC	B
	CALL	GETCH
	JR	Z,NFDRV
	CP	"/"
	LD	A,.IOPT
	RET	Z
	PUSH	BC
	CALL	GET8
	POP	BC
	RET	NZ
	OR	E
	LD	A,.IPARM
	RET	Z
	LD	A,E
	CP	#0A
	LD	A,.IPARM
	RET	NC
	LD	A,(HL)
	OR	A
	JR	NZ,NCI10
	LD	A,E
	EXX
	JR	NSTR

NCI10:	CP	"/"
	JR	Z,NCI20
	CALL	SEP?
	LD	A,.IPARM
	RET	NZ
	CALL	GETCH
	CP	"/"
	LD	A,.INP
	RET	NZ
NCI20:	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"X"
	LD	A,.IOPT
	RET	NZ
	INC	HL
	CALL	CHKEOL
	CALL	Z,GCHKEOL
	RET	NZ
	LD	A,E
	JR	NST10

NFDRV:	LD	A,B
	EXX	; Save drive in B'.
	LD	B,A
	LD	C,_FORMAT
	XOR	A	; Get pointer to prompt string.
	CALL	BDOS
	RET	NZ
	LD	A,H
	OR	L
	JR	Z,NSTR	; Go if no prompt string (A=0).
GETCHR:	LD	A,B	; Get slot number.
	PUSH	BC
	CALL	RDSLOT	; A=character from string.
	POP	BC
	OR	A
	JR	Z,DONSTR	; Go if string has been printed.
	INC	HL	; Next character.
	CALL	PRCHAR	; Print character.
	JR	GETCHR	; Do next character.

DONSTR:	LD	A,"?"
	CALL	PRCHAR
	CALL	SPACE
INCHAR:	LD	C,_CONST	; Get a character, gobbling up chars
	CALL	BDOS	;   in the keyboard buffer.
	PUSH	AF
	LD	C,_INNOE
	CALL	BDOS
	LD	C,A
	POP	AF
	JR	NZ,INCHAR
	LD	A,C
	CP	"9"+1	; If not '1' to '9' to get another.
	JR	NC,INCHAR
	SUB	"1"
	JR	C,INCHAR
	PUSH	AF	; Save choice.
	LD	A,C	; Echo it.
	CALL	PRCHAR
	CALL	LPRINT
	POP	AF
NSTR:	INC	A
	PUSH	AF
	CALL	LPRINT
	LD	A,#2C
	CALL	DMESS
	EXX
	LD	A,B
	EXX
	DEC	A
	LD	C,_CURDRV
	CALL	M,BDOS
	ADD	A,"A"
	CALL	PRCHAR
	LD	A,#2D
	CALL	DMESSCR
	CALL	PAUSE
	POP	AF
	EXX
NST10:	LD	DE,ENVDATA
	LD	HL,(EXITADDR)
	OR	A
	SBC	HL,DE
	EX	DE,HL
	LD	C,_FORMAT
	JP	BDOS

@MEMORY:	AND	(HL)
	LD	A,#00
	LD	(OPTFLAG1),A
	JP	NZ,MEM60
MEM10:	LD	HL,(MAPTAB)
MEM20:	LD	A,(HL)
	OR	A
	JR	Z,MEM40
	PUSH	AF
	INC	HL
	LD	B,(HL)
	CALL	MUL16
	LD	A,#49
	CALL	DMESS
	POP	AF
	LD	B,A
	AND	%00000011
	ADD	A,"0"
	CALL	PRCHAR
	BIT	7,B
	JR	Z,MEM30
	LD	A,"-"
	CALL	PRCHAR
	LD	A,B
	RRA
	RRA
	AND	%00000011
	ADD	A,"0"
	CALL	PRCHAR
MEM30:	CALL	LPRINT
	INC	HL
	LD	B,(HL)
	CALL	MUL16
	LD	A,#06
	CALL	DMESSCR
	INC	HL
	LD	B,(HL)
	CALL	MUL16
	LD	A,#4A
	CALL	DMESSCR
	INC	HL
	LD	B,(HL)
	CALL	MUL16
	LD	A,#4B
	CALL	DMESSCR
	CALL	LPRINT
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	JR	MEM20

MEM40:	LD	HL,(EXITADDR)
	LD	DE,#FFD8
	ADD	HL,DE
	LD	L,#08
	LD	DE,#09
	OR	A
	SBC	HL,DE
	LD	L,#06
	DEC	H
	LD	(VALUEL),HL
	LD	HL,#00
	LD	(VALUEH),HL
	CALL	PRINT32
	LD	A,#4C
	CALL	DMESSCR
	CALL	LPRINT
	CALL	GETBUFLEN
	PUSH	HL
	LD	(VALUEL),HL
	CALL	PRINT32
	LD	A,#4D
	CALL	DMESSCR
	CALL	GETENDADDR
	EX	DE,HL
	POP	HL
	SBC	HL,DE

	LD	DE,BUFADDR
	ADD	HL,DE
	DEC	HL
	LD	(VALUEL),HL
	CALL	PRINT32
	LD	A,#06
	CALL	DMESSCR
	CALL	LPRINT
	CALL	SETPG2
	LD	HL,(ALIEND+#8000)
	CALL	RSTPG2
	SET	7,H
	PUSH	HL
	CALL	GETALIADDR
	SET	7,H
	EX	DE,HL
	POP	HL
	PUSH	HL
	PUSH	DE
	SBC	HL,DE
	LD	(VALUEL),HL
	CALL	PRINT32
	LD	A,#4E
	CALL	DMESSCR
	CALL	SETPG2
	POP	HL
MEM50:	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	DEC	HL
	ADD	HL,BC
	LD	A,B
	OR	C
	JR	NZ,MEM50
	CALL	RSTPG2
	EX	DE,HL
	POP	HL
	SBC	HL,DE
	LD	(VALUEL),HL
	CALL	PRINT32
	LD	A,#06
	CALL	DMESSCR
	CALL	LPRINT
	CALL	SETPG2
	LD	DE,(ALIEND+#8000)
	PUSH	DE
	LD	HL,#3FFF
	SBC	HL,DE
	LD	(VALUEL),HL
	CALL	PRINT32
	LD	A,#4F
	CALL	DMESSCR
	LD	HL,(VAREND+#8000)
	RES	7,H
	POP	DE
	SBC	HL,DE
	LD	(VALUEL),HL
	CALL	RSTPG2
	CALL	PRINT32
	LD	A,#06
	JP	DMESSCR

MEM60:	LD	A,(HL)
	CP	"/"
	LD	A,.IPARM
	RET	NZ
	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"P"
	JR	Z,MEM70
	CP	"K"
	JR	Z,MEM90
	LD	A,.IOPT
	RET

MEM70:	CALL	SETP
MEM80:	INC	HL
	CALL	GETCH
	JR	NZ,MEM60
	JP	MEM10

MEM90:	LD	A,#01
	LD	(OPTFLAG1),A
	JR	MEM80

MUL16:	PUSH	HL
	PUSH	DE
	LD	HL,#00
	LD	(VALUEL),HL
	LD	(VALUEH),HL
	LD	DE,#4000
	INC	B
	DEC	B
	JR	Z,MUL60
MUL40:	LD	HL,(VALUEL)
	ADD	HL,DE
	LD	(VALUEL),HL
	JR	NC,MUL50
	LD	HL,(VALUEH)
	INC	HL
	LD	(VALUEH),HL
MUL50:	DJNZ	MUL40
MUL60:	POP	DE
	POP	HL
PRINT32:	LD	A,(OPTFLAG1)
	BIT	0,A
	JR	NZ,PRI10
	PUSH	HL
	PUSH	DE
	LD	IX,XBUF1
	PUSH	IX
	LD	DE,VALUEL
	LD	A," "
	CALL	D32
	POP	HL
	PUSH	HL
	INC	HL
	INC	HL
	LD	C," "
	CALL	INSBYTE
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	CALL	INSBYTE
	POP	DE
	CALL	PRTSTR
	LD	A,#48
	CALL	DMESS
	POP	DE
	POP	HL
	RET

PRI10:	PUSH	HL
	PUSH	DE
	LD	A," "
	CALL	PRLEN2
	POP	DE
	POP	HL
	RET

@GOTO:	LD	A,(BATHNDL)
	CP	#FE
	LD	A,.BADCM
	RET	NZ
	LD	A,(HL)
	OR	A
	LD	A,.NOPAR
	RET	Z
	PUSH	HL
GOT80:	LD	HL,#00
	LD	(BATLINADDR),HL
GOT90:	CALL	INBAT
	JR	Z,GOT100
	POP	HL
	CP	.EOF
	RET	NZ
	CALL	END10
	LD	A,#FF
	LD	(STRCODE),A
	LD	A,.IPARM
	RET

GOT100:	JR	NC,GOT90
	LD	HL,ENVDATA+1
	CALL	GETCH
	POP	BC
	PUSH	BC
	CALL	STRCMP
	JR	NZ,GOT90
	POP	HL
	RET

@END:	LD	A,(BATHNDL)
	CP	#FE
	LD	A,.BADCM
	RET	NZ
	LD	A,(HL)
	OR	A
	LD	A,.INP
	RET	NZ
END10:	LD	HL,#00
	LD	(BATLINADDR),HL
	LD	A,(BATPAGE)
	LD	E,#1A
	JP	WR_SEG

@GOSUB:	LD	A,(BATHNDL)
	CP	#FE
	LD	A,.BADCM
	RET	NZ
	LD	A,(HL)
	OR	A
	LD	A,.NOPAR
	RET	Z
	PUSH	HL
	LD	HL,(GOSUBADDR)
	LD	DE,GOSUBLIST+16
	OR	A
	SBC	HL,DE
	POP	HL
	LD	A,.INP
	RET	Z
	PUSH	HL
	LD	HL,(GOSUBADDR)
	LD	DE,(BATLINADDR)
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(GOSUBADDR),HL
	JR	GOT80

@RETURN:	LD	A,(BATHNDL)
	CP	#FE
	LD	A,.BADCM
	RET	NZ
	PUSH	HL
	LD	HL,(GOSUBADDR)
	LD	DE,GOSUBLIST
	PUSH	HL
	SBC	HL,DE
	POP	HL
	JR	Z,RET10
	DEC	HL
	LD	D,(HL)
	DEC	HL
	LD	E,(HL)
	LD	(GOSUBADDR),HL
	EX	DE,HL
	LD	(BATLINADDR),HL
RET10:	POP	HL
	LD	A,(HL)
	OR	A
	RET	Z
	PUSH	HL
	JP	GOT80

@IF:	CALL	COND2
	RET	NZ
	JR	C,EXEC2
	XOR	A
	RET

EXEC2:	LD	DE,ENVDATA
	PUSH	DE
	CALL	NCOPY
	POP	DE
	CALL	ALIASING
	RET	NZ
	LD	HL,(NEXTADDR)
	LD	A,H
	OR	L
	CALL	Z,MULTICMD
	EX	DE,HL
	PUSH	HL
	CALL	UNQUOTE
	POP	HL
	JP	DO_CMD

COND2:	CALL	COND
	RET	NZ
	CCF
	SBC	A,A
	EX	AF,AF'
	PUSH	HL
	EXX
	POP	HL
	CALL	STRIP
	LD	BC,ENVDATA
	PUSH	BC
	CALL	CPYSTR
	POP	BC
	RET	NZ
	PUSH	HL
	PUSH	BC
	LD	HL,$AND
	CALL	COMPARE3
	POP	BC
	POP	HL
	JR	NZ,CON10
	CALL	STRIP
	EX	AF,AF'
	PUSH	AF
	CALL	COND2
	POP	BC
	RET	NZ
	AND	B
	CP	A
	RRA
	RET

CON10:	PUSH	HL
	PUSH	BC
	LD	HL,$OR
	CALL	COMPARE3
	POP	BC
	POP	HL
	JR	NZ,CON20
	CALL	STRIP
	EX	AF,AF'
	PUSH	AF
	CALL	COND2
	POP	BC
	RET	NZ
	OR	B
	CP	A
	RRA
	RET

CON20:	PUSH	HL
	PUSH	BC
	LD	HL,$XOR
	CALL	COMPARE3
	POP	BC
	POP	HL
	JR	NZ,CON30
	CALL	STRIP
	EX	AF,AF'
	PUSH	AF
	CALL	COND2
	POP	BC
	RET	NZ
	XOR	B
	CP	A
	RRA
	RET

CON30:	EXX
	EX	AF,AF'
	CP	A
	RRA
	RET

@IFF:	PUSH	HL
	LD	HL,(IFFADDR)
	LD	DE,IFFLIST+16
	CALL	COMPARE4
	JR	Z,IFF20
	LD	A,(HL)
	INC	HL
	LD	(IFFADDR),HL
	LD	(HL),A
	EX	DE,HL
	POP	HL
	LD	B,A
	PUSH	BC
	PUSH	DE
	CALL	COND2
	CCF
	POP	DE
	POP	BC
	RET	NZ
	BIT	0,B
	JR	Z,IFF10
	DEFB	#3E
IFF10:	SBC	A,A
	LD	(DE),A
	LD	A,(HL)
	OR	A
	RET	Z
	JP	EXEC2

IFF20:	POP	HL
	LD	A,.INP
	RET

@THEN:	AND	(HL)
	RET	Z
	JP	EXEC2

@ELSE:	PUSH	HL
	LD	HL,(IFFADDR)
	LD	DE,IFFLIST
	CALL	COMPARE4
	JR	Z,ELS10
	LD	A,(HL)
	CP	#9F
	JR	Z,ELS10
	CPL
	LD	(HL),A
ELS10:	POP	HL
	LD	A,(HL)
	OR	A
	RET	Z
	JP	EXEC2

@ENDIFF:	PUSH	HL
	LD	HL,(IFFADDR)
	LD	DE,IFFLIST
	CALL	COMPARE4
	JR	Z,END20
	DEC	HL
	LD	(IFFADDR),HL
END20:	POP	HL
	LD	A,(HL)
	OR	A
	RET	Z
	JP	EXEC2

COND:	LD	BC,ENVDATA
	PUSH	BC
	CALL	MKPATH2
	POP	BC
	RET	NZ	; Return if error
	EX	DE,HL
	LD	HL,$NOT
	CALL	COMPARE3
	EX	DE,HL
	JR	NZ,EXIST?
	CALL	COND10
	CCF	; Reverse GO condition
	RET

COND10:	CALL	GETCH
	LD	BC,ENVDATA
	CALL	MKPATH2
	RET	NZ
EXIST?:	LD	BC,ENVDATA
	EX	DE,HL
	LD	HL,$EXIST
	CALL	COMPARE3
	EX	DE,HL
	JR	NZ,EQUAL?
	CALL	GETCH
	CALL	PRS	; Get path string.
	RET	NZ	; Return if error.
	BIT	3,B
	LD	A,.NOFIL
	JR	Z,EX10
	LD	C,(HL)	; Save terminating char.
	LD	(HL),#00	; Terminate path.
	PUSH	HL
	PUSH	BC
	LD	IX,FIB1
	LD	BC,#0640
	CALL	BDOS
	POP	BC	; Restore terminating char.
	POP	HL	;   in case this was the end of line.
	LD	(HL),C
EX10:	OR	A
	RET	Z	; Z & NC => if no error
	CP	.NODIR
	SCF
	RET	Z	; Z & C => if directory not found
	CP	.NOFIL
	SCF	; Z & C => if file not found,
	RET	; NZ otherwise.

EQUAL?:	CALL	STRIP
	LD	A,(HL)
	CALL	MKUPPER
	CP	"="
	JR	NZ,EQU10
	INC	HL
	LD	A,(HL)
	CP	"="
	JP	NZ,EQU80
	LD	A,#01
	JR	EQU40

EQU10:	CP	"E"
	JR	NZ,EQU20
	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"Q"
	JR	NZ,EQU80
	LD	A,#01
	JR	EQU40

EQU20:	CP	"G"
	JR	NZ,EQU30
	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"T"
	JR	NZ,EQU80
	LD	A,#02
	JR	EQU40

EQU30:	CP	"L"
	JR	NZ,EQU80
	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"T"
	JR	NZ,EQU80
	LD	A,#03
EQU40:	EX	AF,AF'
	INC	HL
	CALL	STRIP
	LD	BC,ENVDATA+#80
	PUSH	BC
	CALL	MKPATH2
	POP	BC
	RET	NZ
	EX	DE,HL
	LD	HL,ENVDATA
	CALL	STRCMP
	EX	DE,HL
	EX	AF,AF'
	DEC	A
	JR	Z,EQU70
	DEC	A
	JR	Z,EQU60
	DEC	A
	EX	AF,AF'
	JR	NZ,EQU50
	SCF
	RET

EQU50:	LD	A,#00
	BIT	0,A
	RET

EQU60:	EX	AF,AF'
	LD	A,#00
	BIT	0,A
	CCF
	RET

EQU70:	EX	AF,AF'
	RET	Z
	CP	A
	SCF
	RET

EQU80:	POP	HL
	LD	A,.IPARM
	OR	A
	RET

STRCMP:	LD	A,(BC)
	CP	(HL)
	RET	NZ
	INC	BC
	INC	HL
	OR	A
	JR	NZ,STRCMP
	RET

CHKEQ:	LD	A,(HL)
	OR	A
	RET	Z
	LD	A,(BC)
	CP	(HL)
	RET	NZ
	INC	BC
	INC	HL
	OR	A
	JR	NZ,CHKEQ
	RET

COMPARE3:	LD	A,(BC)
	CALL	MKUPPER
	CP	(HL)
	RET	NZ
	INC	BC
	INC	HL
	OR	A
	JR	NZ,COMPARE3
	RET

COMPARE4:	LD	A,H
	SUB	D
	RET	NZ
	LD	A,L
	SUB	E
	RET

$NOT:	DEFB	"NOT",0
$EXIST:	DEFB	"EXIST",0
$AND:	DEFB	"AND",0
$OR:	DEFB	"OR",0
$XOR:	DEFB	"XOR",0

@COLOR:	AND	(HL)
	LD	A,.NOPAR
	RET	Z
	CALL	GET8
	RET	NZ
	LD	A,E
	CP	#10
	JR	NC,GOT120
	LD	(FORCLR),A
	CALL	GETCH
	JR	Z,COL10
	CALL	GET8
	RET	NZ
	LD	A,E
	CP	#10
	JR	NC,GOT120
	LD	(BAKCLR),A
	CALL	GETCH
	JR	Z,COL10
	CALL	GET8
	CALL	Z,CHKNO
	CALL	Z,CHKEOL
	RET	NZ
	LD	A,E
	CP	#10
	JR	NC,GOT120
	LD	(BDRCLR),A
COL10:	LD	IX,#62
	JR	GOT110

@MODE:	AND	(HL)
	LD	A,.NOPAR
	RET	Z
	LD	A,(CRTCNT)
	LD	(XBUF1),A
	CALL	GET8
	RET	NZ
	CALL	GETCH
	JR	Z,MOD10
	PUSH	DE
	CALL	GET8
	LD	C,E
	POP	DE
	CALL	Z,CHKNO
	CALL	Z,CHKEOL
	RET	NZ
	LD	A,C
	LD	(XBUF1),A
	XOR	A
MOD10:	OR	E
	JR	Z,GOT120
	CP	#51
	JR	NC,GOT120
	LD	IX,#6C
	LD	HL,LINL40
	CP	#21
	JR	NC,GOTCOLS
	LD	IX,#6F
	INC	HL
GOTCOLS:	LD	(HL),A
	LD	A,(XBUF1)
	OR	A
	JR	Z,GOT120
	CP	#1B
	JR	NC,GOT120
	LD	(CRTCNT),A
GOT110:	JP	CALLSLOT

GOT120:	LD	A,.IPARM
	RET

@INKEY:	SCF
@INPUT:	EX	AF,AF'
	XOR	A
	LD	(ENVNAME),A
	OR	(HL)
	LD	A,.NOPAR
	RET	Z
	CALL	PRSENV
	JR	NZ,INP10
	CALL	GETCH
	JR	Z,INP30
INP10:	LD	DE,ENVDATA
INP20:	LD	A,(HL)
	OR	A
	JR	Z,INP30
	CP	"%"
	JR	Z,INP30
	LD	(DE),A
	INC	DE
	INC	HL
	JR	INP20
INP30:	PUSH	AF
	XOR	A
	LD	(DE),A
	POP	AF
	OR	A
	CALL	NZ,PRSENV
	LD	A,.INP
	RET	NZ
	CALL	GETCH
	LD	A,.INP
	RET	NZ
	LD	A,(ENVNAME)
	OR	A
	LD	A,.NOPAR
	RET	Z
	LD	DE,ENVDATA
	CALL	PRTSTR
	EX	AF,AF'
	JR	NC,INP40
	CALL	INCH
	LD	A,L
	LD	HL,ENVDATA
	LD	(HL),A
	INC	HL
	LD	(HL),0
	DEC	HL
	EX	DE,HL
	JR	INP50
INP40:	LD	HL,ENVDATA
	LD	(HL),#7F
	EX	DE,HL
	LD	C,_BUFIN
	CALL	BDOS
	CALL	LPRINT
	LD	HL,ENVDATA+1
	PUSH	HL
	LD	C,(HL)
	LD	B,0
	INC	HL
	ADD	HL,BC
	LD	(HL),0
	POP	DE
	INC	DE
INP50:	LD	HL,ENVNAME
	LD	C,_SENV
	JP	BDOS

PRSENV:	LD	A,(HL)
	CP	"%"
	RET	NZ
	LD	DE,ENVNAME
PRS60:	INC	HL
	LD	A,(HL)
	OR	A
	JR	Z,PRS70
	CP	" "
	JR	Z,PRS70
	LD	(DE),A
	INC	DE
	JR	PRS60
PRS70:	XOR	A
	LD	(DE),A
	RET

@RESET:	AND	(HL)
	LD	A,.INP
	RET	NZ
	LD	IY,(EXPTBL-1)
	LD	SP,#F51F
	LD	IX,#00
	JP	CALSLT

@CDPATH:	PUSH	HL
	LD	HL,CDPATH$
	JR	PAT10

@PATH:	PUSH	HL
	LD	HL,PATH$
PAT10:	PUSH	HL
	EXX
	POP	HL
	EXX
	CALL	GENV2
	POP	HL
	RET	NZ
	OR	(HL)
	JP	Z,?DMSCR
	INC	HL
	CP	"-"
	JR	Z,DELP
	CP	"+"
	JR	Z,ADDP
	XOR	A
	LD	(DE),A
	DEC	HL
ADDP:	EX	DE,HL	; HL -> current PATH string.
	PUSH	HL	; If only separators there, then set
	CALL	GETCH	;   the PATH string to a null string.
	POP	HL	;   This fiddle is done because the
	JR	NZ,PTH10	;   PATH string is initialised to '; '.
	LD	(HL),A
PTH10:	EX	DE,HL
AP10:	CALL	GETCH	; Skip separators.
	JR	Z,APC10	; Set new path if end of user's items.
	LD	BC,XBUF1
	PUSH	BC
	CALL	CPYSTR	; Copy & uppercase item, HL -> next.
	PUSH	HL	; Save ptr to next item in user string.
	CALL	NC,DELSTR	; Delete item if it exists.
	POP	HL
	POP	BC	; BC -> item copied to BUFF3.
	RET	C	; Return if error.
	LD	DE,ENVDATA-1	; Find end of current PATH string,
AP20:	INC	DE	;   then append separator and the new
	LD	A,(DE)	;   item.
	OR	A
	JR	NZ,AP20
	LD	A,";"	; Add separator to PATH string.
	LD	(DE),A
	INC	DE
	LD	A," "
	LD	(DE),A
AP30:	INC	DE
	LD	A,(BC)
	INC	BC
	LD	(DE),A
	OR	A
	JR	NZ,AP30
	JR	AP10

APC10:	EXX
	PUSH	HL
	EXX
	POP	HL
	JP	SENV2

DELP:	CALL	GETCH	; Skip separators.
	JR	Z,APC10	; Attempt to set PATH if end of items.
	LD	BC,XBUF1	; Else copy to BUFF3 & upper case.
	CALL	CPYSTR	; HL -> start of next item.
	PUSH	HL	; Save pointer to next item.
	CALL	NC,DELSTR	; Attempt to delete item from string.
	POP	HL
	RET	C	; Return if error.
	LD	A,.IPATH	; Return .IPATH if item not found.
	RET	Z
	JR	DELP	; Repeat for next item.

DELSTR:	LD	HL,ENVDATA
DS5:	PUSH	HL	; Save start of this item.
	POP	IX
	CALL	GETCH	; Skip leading separators.
	RET	Z	; Return with Z if user item not found.
	LD	BC,XBUF1+#80	; Copy item to BUFF3+128 & upper case.
	PUSH	BC
	CALL	CPYSTR	; Leaves HL -> next item.
	POP	BC
	RET	C
	LD	DE,XBUF1	; Compare with string at BUFF3.
DS10:	LD	A,(BC)
	EX	DE,HL
	CP	(HL)
	EX	DE,HL
	JR	NZ,DS5
	INC	DE
	INC	BC
	OR	A
	JR	NZ,DS10
	PUSH	IX
	POP	DE
	CALL	NCOPY
	INC	A
	RET

CPYSTR:	LD	D,#00	; Zero character flags.
CS10:	LD	E,(HL)
	PUSH	BC
	PUSH	HL
	LD	C,_CHKCHR
	CALL	BDOS
	POP	HL
	POP	BC
	SCF
	RET	NZ
	LD	(BC),A
	OR	E
	RET	Z
	CALL	SEP?
	RET	Z
	LD	A,E
	LD	(BC),A
	INC	BC
	INC	HL
	JR	CS10

MKPATH2:	LD	D,#01
	XOR	A
	LD	(VALUEL),A
MKP10:	LD	A,(HL)
	CP	"{"
	JR	NZ,MKP20
	LD	(VALUEL),A
	INC	HL
	JR	MKP10
MKP20:	CP	"}"
	JR	NZ,MKP30
	XOR	A
	LD	(VALUEL),A
	INC	HL
	JR	MKP10
MKP30:	LD	E,(HL)
	PUSH	BC
	PUSH	HL
	LD	C,_CHKCHR
	CALL	BDOS
	POP	HL
	POP	BC
	SCF
	RET	NZ
	LD	(BC),A
	OR	E
	RET	Z
	LD	A,(VALUEL)
	OR	A
	LD	A,E
	CALL	Z,SEP?
	RET	Z
	LD	A,E
	LD	(BC),A
	INC	BC
	INC	HL
	JR	MKP10

		SUBTTL	PAUSE
;        The  PAUSE  command is similar to the ECHO command, except that after
; printing the message on the reast of the command line, it prompts for a  key
; to be pressed.  This is used in batch file processing  to  prompt  for,  for
; example,  the user to change disks. The entry point PAUSE is called from the
; character output routine OUTCH at the end of a screenful ot text if /P is in
; effect.
@PAUSE:	EX	DE,HL	; DE -> command arguments.
	CALL	?DMSCR	; Print arguments & CR,LF if non-null.
PAUSE:	LD	A,#0F
	CALL	DMESS
	JP	INCH

@RAMDISK:	AND	(HL)
	JR	NZ,SETRAM
	LD	BC,#FF68
	CALL	BDOS
	RET	NZ
	LD	H,A
	OR	B
	LD	A,.NRAMD
	RET	Z
	LD	L,B
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	LD	A,#29
	CALL	DMESS
	LD	IX,ENVDATA
	PUSH	IX
	CALL	D16
	POP	DE
	CALL	PRTSTR
	LD	A,"K"
	CALL	PRCHAR
	JP	LPRINT

SETRAM:	EX	AF,AF'
	CALL	CHKD	; Check for /D.
	RET	NZ	; Ret if error.
	EX	AF,AF'
	JR	NZ,ND	; Go if not.
	OR	(HL)	; Any number given ?
	LD	B,A
	JR	Z,NRAM	; Just delete RAM disk if not.
	XOR	A	; Else AF' = Z again, get number.
ND:	EX	AF,AF'
	CALL	GET16	; Get size of RAM disk required.
	RET	NZ
	LD	A,(HL)	; Allow 'K' to be given after number.
	CALL	UC
	CP	"K"
	JR	NZ,NK
	INC	HL	; Skip passed K if given.
NK:	LD	A,(HL)	; Get character after number.
	CP	"/"	; Start of /D ?
	CALL	NZ,CHKNO	; Check for garbage if not.
	CALL	Z,CHKD	; Check for /D if no error.
	RET	NZ	;   if not.
	CALL	GETCH	; Check for garbage on end of line.
	LD	A,.INP	; 'Too many parameters' if not eol.
	RET	NZ
	LD	B,#04
	LD	HL,#0F	; Round up to next 16K boundary.
	ADD	HL,DE
DIV16:	SRL	H	; Divide by 16 for no. segments.
	RR	L
	DJNZ	DIV16
	LD	A,.IPARM	; If > 254 16K segments, then give
	INC	H	;   error.
	DEC	H
	RET	NZ
	LD	B,L	; B=no. segments in new RAM disk.
	INC	L
	RET	Z	; Ret if 255 segments specified.
	EXX	; Save new size in B'.
	EX	AF,AF'
	JR	Z,DELRAM	; Destroy existing RAM disk if yes.
	LD	BC,#FF68
	CALL	BDOS	; See if RAM disk already exists.
	RET	NZ	; Return any errors.
	OR	B	; NZ => RAM disk currently exists.
	JR	Z,NEWRAM	; Create one if one doesn't exist.
	LD	A,#34
	CALL	YN	; Prompt with 'Delete RAM disk (Y/N) ?'
	LD	A,#00
	RET	Z	; Ret with no error if 'N' pressed.
DELRAM:	LD	BC,_RAMDISK	; Delete current RAM disk.
	CALL	BDOS
	RET	NZ
NEWRAM:	EXX	; B=size of new RAM disk.
NRAM:	LD	C,_RAMDISK	; Create new RAM disk.
	JP	BDOS

CHKD:	LD	A,(HL)	; Start of option ?
	CP	"/"
	JR	NZ,OKRET	; Return no error if not.
	INC	HL
	LD	A,(HL)	; Else get option character.
	CALL	UC
	CP	"D"	; /D ?
	LD	A,.IOPT
	RET	NZ	; Return 'invalid option' error if not.
	INC	HL
	XOR	A
	EX	AF,AF'
	CALL	GETCH	; Skip following separators.
	JR	CHKD	; Repeat so invalid /s give .IOPT.

OKRET:	XOR	A
	RET

		SUBTTL	SET
;        This is the SET command routine.  SET  alone  prints  out  the  whole
; environment,  SET followed by a name prints out the string for that name and
; SET followed by a name, separator and string sets that environment  name  to
; the string.
@SET:	AND	(HL)	; Any name given ?
	JR	NZ,DST10	; Go if yes, else print environment.
SET10:	LD	HL,#01	; Initialise item number.
DENV:	PUSH	HL	; Save item number.
	EX	DE,HL
	CALL	FENV	; Get name of item.
	JR	NZ,NXTENV	; Ignore this item if error.
	POP	BC
	OR	(HL)	; Null name ?
	RET	Z	; Done if yes.
	PUSH	BC
	CALL	GENV	; Get string value of this name.
	JR	NZ,NXTENV	; Ignore this item if error.
	EX	DE,HL	; DE -> name.
	CALL	PRTSTR	; Print name of string.
	LD	A,#41
	CALL	DMESS	; Print '='.
	EX	DE,HL	; DE -> value of name.
	CALL	DMSCR	; Followed by the string & CR,LF.
NXTENV:	POP	HL	; Get back current item number.
	INC	HL	; Next item.
	JR	DENV

SETNAME:	PUSH	HL	; HL -> start of name.
	LD	D,#00	; Zero character flags.
	DEC	HL
NXTCHR:	INC	HL
	LD	E,(HL)
	PUSH	HL
	LD	C,_CHKCHR
	CALL	BDOS
	POP	HL
	POP	BC
	RET	NZ
	PUSH	BC
	OR	E
	JR	Z,DSTR
	CALL	SEP?
	JR	NZ,NXTCHR
	PUSH	HL
	CALL	STRIP
	POP	HL
	LD	(HL),#00
	JR	Z,DSTR
	INC	HL
	CALL	GETCH
	EX	DE,HL
	POP	HL
	LD	C,_SENV
	JP	BDOS

DSTR:	POP	HL	; HL -> start of name.
	CALL	GENV2
	RET	NZ
?DMSCR:	LD	A,(DE)
	OR	A
	RET	Z
	JP	DMSCR

DST10:	LD	A,(HL)
	CP	"/"
	JR	NZ,SETNAME
	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"P"
	LD	A,.IOPT
	RET	NZ
	CALL	SETP
	INC	HL
	CALL	GETCH
	JR	NZ,SETNAME
	JR	SET10

@ALIAS:	AND	(HL)
	JR	NZ,ALI180
ALI130:	LD	BC,#00
ALI140:	LD	HL,ENVNAME
	LD	DE,ENVDATA
	CALL	FNDALIAS
	LD	A,(HL)
	OR	A
	RET	Z
	PUSH	BC
	EX	DE,HL
	CALL	PRTSTR
	LD	A,#41
	CALL	DMESS
	EX	DE,HL
	CALL	DMSCR
	POP	BC
	JR	ALI140

ALI150:	PUSH	HL
	LD	D,#00
	DEC	HL
ALI160:	INC	HL
	LD	E,(HL)
	PUSH	HL
	LD	C,_CHKCHR
	CALL	BDOS
	POP	HL
	LD	(HL),E
	POP	BC
	RET	NZ
	PUSH	BC
	OR	E
	JR	Z,ALI170
	CALL	SEP?
	JR	NZ,ALI160
	PUSH	HL
	CALL	STRIP
	POP	HL
	LD	(HL),#00
	JR	Z,ALI170
	INC	HL
	CALL	GETCH
	EX	DE,HL
	POP	HL
	JP	SETALIAS

ALI170:	POP	HL
	LD	DE,ENVDATA
	CALL	GETALIAS
	JP	?DMSCR

ALI180:	LD	A,(HL)
	CP	"/"
	JR	NZ,ALI150
	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"S"
	JR	Z,ALI200
	CP	"L"
	JR	Z,ALI250
	CP	"R"
	JP	Z,ALI260
	CP	"P"
	JR	Z,ALI190
	DEC	HL
	JR	ALI150

ALI190:	CALL	SETP
	INC	HL
	CALL	GETCH
	JR	NZ,ALI150
	JR	ALI130

ALI200:	CALL	PRSPATH
	OR	A
	RET	NZ
	LD	BC,_CREATE
	CALL	BDOS
	RET	NZ
	PUSH	BC
	LD	C,_WRITE
	LD	DE,TALIAS$
	LD	HL,#0C
	CALL	BDOS
	POP	BC
	RET	NZ
	PUSH	BC
	CALL	SETPG2
	CALL	GETALIADDR
	SET	7,H
ALI210:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	DEC	HL
	LD	A,D
	OR	E
	JR	Z,ALI220
	ADD	HL,DE
	JR	ALI210

ALI220:	PUSH	HL
	CALL	GETALIADDR
	SET	7,H
	DEC	HL
	DEC	HL
	EX	DE,HL
	POP	HL
	SBC	HL,DE
	INC	DE
	INC	DE
	POP	BC
	PUSH	BC
	LD	C,_WRITE
ALI230:	CALL	BDOS
	LD	E,A
	POP	BC
ALI240:	PUSH	DE
	LD	C,_CLOSE
	CALL	BDOS
	PUSH	AF
	CALL	RSTPG2
	POP	AF
	POP	DE
	RET	NZ
	LD	A,E
	RET

ALI250:	CALL	PRSPATH
	OR	A
	RET	NZ
	LD	C,_OPEN
	CALL	BDOS
	RET	NZ
	PUSH	BC
	LD	C,_READ
	LD	DE,ENVNAME
	LD	HL,#0C
	CALL	BDOS
	POP	BC
	RET	NZ
	PUSH	BC
	LD	HL,ENVNAME
	LD	BC,TALIAS$
	CALL	STRCMP
	POP	BC
	LD	E,.IFNM
	JR	NZ,ALI240
	PUSH	BC
	CALL	SETPG2
	POP	BC
	PUSH	BC
	LD	HL,(ALIADDR+#8000)
	SET	7,H
	EX	DE,HL
	LD	HL,(ALIEND+#8000)
	SET	7,H
	OR	A
	SBC	HL,DE
	LD	C,_READ
	JR	ALI230

ALI260:	INC	HL
	CALL	GETCH
	LD	A,.INP
	RET	NZ
	CALL	GETALIADDR
	XOR	A
	CALL	WRCHR
	INC	HL
	CALL	WRCHR
	RET

TALIAS$:	DEFB	"Alias File",26,0

PRSPATH:	INC	HL
	CALL	GETCH
	LD	A,.NOPAR
	RET	Z
	LD	BC,_PARSE
	EX	DE,HL
	PUSH	DE
	CALL	BDOS
	POP	HL
	RET	NZ
	EX	DE,HL
	LD	A,(HL)
	OR	A
	JR	Z,PRS80
	CP	" "
	LD	A,.IPATH
	RET	NZ
	LD	(HL),#00
	INC	HL
	CALL	GETCH
	LD	A,.INP
	RET	NZ
PRS80:	XOR	A
	RET

@HISTORY:	AND	(HL)
	JP	Z,HIS30
	LD	A,(HL)
	CP	"/"
	JP	Z,CHECKP
	CALL	GET16
	CALL	Z,GCHKEOL
	RET	NZ
	EX	DE,HL
	LD	DE,(MAXBUFLEN)
	CALL	COMPARE4
	LD	A,.BADNO
	RET	NC
	LD	DE,128
	CALL	COMPARE4
	LD	A,.BADNO
	RET	C
	CALL	SETBUFLEN	; stel nieuwe bufferlengte in
	LD	DE,BUFADDR	; start van buffer
	ADD	HL,DE	; tel lengte erbij
	PUSH	HL	; dit is start van aliasbuffer
	CALL	GETALIADDR	; haal huidige aliasbuffer
	POP	DE	; nieuw start adres
	CALL	COMPARE4	; zijn die gelijk?
	RET	Z	; ja, dan zijn we klaar
	EX	AF,AF'                  ; bewaar vergelijking voor later
	SET	7,H	; echte adres in geheugen
	PUSH	HL	; bewaar dit
	CALL	SETPG2	; schakel pagina 2 permanent in
HIS10:	LD	C,(HL)	; lengte van deze alias
	INC	HL
	LD	B,(HL)
	DEC	HL
	ADD	HL,BC	; tel bij adres op
	LD	A,B	; is lengte nul?
	OR	C
	JR	NZ,HIS10	; nee, dan volgende
	INC	HL
	INC	HL	; eind adres aliasbuffer
	PUSH	HL	; bewaar dit in HL'
	EXX
	POP	HL
	EXX
	POP	DE	; haal startadres aliasbuffer
	PUSH	DE	; en bewaar weer
	SBC	HL,DE	; trek van eindadres af
	LD	B,H	; dit is dus de lengte
	LD	C,L
	PUSH	BC	; bewaar de lengte
	EXX
	PUSH	HL
	EXX
	CALL	GETBUFLEN	; haal lengte van buffer
	LD	DE,BUFADDR	; startadres van buffer
	ADD	HL,DE	; tel op
	EX	DE,HL	; naar DE
	PUSH	DE
	EXX
	POP	HL	; en terug in HL'
	POP	DE	; ook DE' terug
	POP	BC	; en BC'
	ADD	HL,BC	; tel lengte bij startadres aliasbuffer
	EX	DE,HL
	EXX
	POP	HL	; startadres aliasbuffer terug
	EX	AF,AF'                  ; resultaat van vergelijking
	JR	C,HIS20	; C betekent achteruit kopieren
	PUSH	DE	; bewaar nieuwe startadres
	SET	7,D	; maak echte adres
	LDIR		; kopieer
	CALL	RSTPG2	; zet pagina 2 terug
	POP	HL	; haal nieuwe startadres terug
	CALL	SETALIADDR	; en stel dit in
	JR	CHE10	; wis history buffer

HIS20:	EXX		; haal alternatieve registers
	DEC	HL
	DEC	DE
	SET	7,D	; maak echte adres
	LDDR		; en kopieer achteruit
	CALL	GETBUFLEN	; lengte buffer
	LD	DE,BUFADDR	; start buffer
	ADD	HL,DE	; tel op
	PUSH	HL	; bewaar start aliasbuffer
	CALL	RSTPG2	; zet pagina 2 terug
	POP	HL	; haal terug
	CALL	SETALIADDR	; dit is nieuwe startadres aliasbuffer
	JR	CHE10	; wis history buffer

HIS30:	CALL	GETRDADDR
	LD	(VALUEL),HL
	CALL	GETPUTADDR
	LD	DE,BUFADDR
	CALL	COMPARE4
	RET	Z
	CALL	SETRDADDR
	CALL	HISPREV
	CALL	GETRDADDR
	LD	D,H
	LD	E,L
HIS40:	CALL	HISNEXT
	JR	NZ,HIS60
HIS50:	CALL	GETRDADDR
	CALL	COMPARE4
	JR	NZ,HIS40
	LD	HL,(VALUEL)
	CALL	SETRDADDR
	XOR	A
	RET

HIS60:	CALL	Z,LPRINT
	JR	Z,HIS50
	CALL	PRCHAR
	CALL	HISNEXT
	JR	HIS60

CHECKP:	INC	HL
	LD	A,(HL)
	CALL	MKUPPER
	CP	"D"
	JR	Z,CHECKD
	CP	"P"
	LD	A,.IOPT
	RET	NZ
	INC	HL
	CALL	SETP
	CALL	GETCH
	JR	Z,HIS30
	LD	A,.INP
	RET

CHECKD:	INC	HL
	CALL	GETCH
	LD	A,.INP
	RET	NZ
CHE10:	LD	HL,BUFADDR
	CALL	SETPUTADDR
	CALL	SETRDADDR
	DEC	HL
	CALL	SETENDADDR
	XOR	A
	RET

		SUBTTL	TIME
;        This is the TIME command routine. The time is  printed  using  DTIME,
; which  prints  the  time  as  printed  by DIR ie. excluding seconds, so this
; routine prints seconds afterwards. DTIME  prints  the  time  in  the  format
; defined  by  the  TIME environment string, but this routine does not need to
; know about this since the time can be input in either format  unambiguously.
; Although  100ths  of  a  second  are  not  printed,  they  are accepted when
; inputting the time.
@TIME:	PUSH	HL	; Save pointer to command line.
	CALL	TFORM	; Set up TM_FORM, the time format var.
	POP	HL
	LD	A,(HL)
	OR	A	; New time given on command line ?
	JR	NZ,RTIM	; Attempt to set new time if yes.
	LD	A,#24	; Print 'Current time is'
	CALL	DMESS
	LD	C,_GTIME	; Get current time for printing.
	CALL	BDOS
	PUSH	DE	; Save seconds in D.
	LD	A,L	; Convert hours & mins to FIB format.
	ADD	A,A
	ADD	A,A
	LD	B,#03
TIM2:	ADD	A,A
	RL	H
	DJNZ	TIM2
	LD	C,H
	LD	HL,ENVNAME
	LD	(HL),A
	INC	HL
	LD	(HL),C
	LD	IX,ENVNAME+2
	PUSH	IX
	CALL	DTIME
	POP	DE
	POP	BC
	PUSH	AF
	CALL	PRTSTR
	LD	A,":"
	CALL	PRCHAR
	LD	A,B
	LD	D,#FF
	CALL	DDT
	POP	AF
	CP	" "
	CALL	NZ,PRCHAR
	LD	A,#0E
	CALL	DMESSCR
NEWTIM:	LD	A,#26	; Print 'Enter new time:'.
	CALL	DMESS
	CALL	INLI	; Input a line.
	JR	Z,TIM5	; Go if no error.
	CP	.EOF
	RET	NZ	; Return if not end of file error.
TIM5:	INC	HL	; Point passed length byte.
	CALL	GETCH	; Skip leading separators.
	RET	Z	; Just return if new time not given.
RTIM:	EXX	; Hide the input line pointer.
	LD	C,_GTIME	; Get current values for defaults.
	CALL	BDOS
	EXX	; Save current values, get input ptr.
	CALL	GETNO	; Get hours.
	JR	C,TIM10	; Go if invalid number.
	EXX
	LD	H,A	; Else save new hours.
	EXX
TIM10:	CALL	DTSKIP	; Skip separators.
	CALL	NC,GETNO	; Get minutes.
	JR	C,TIM20	; Go if invalid number.
	EXX
	LD	L,A	; Else save new minutes.
	EXX
TIM20:	CALL	DTSKIP	; Skip separators.
	CALL	NC,GETNO	; Get seconds.
	JR	C,TIM30	; Go if invalid number.
	EXX
	LD	D,A	; Else save new number.
	EXX
TIM30:	CALL	DTSKIP	; Skip separators.
	CALL	NC,GETNO	; Get 100ths.
	JR	C,TIM35	; Go if invalid number.
	EXX
	LD	E,A	; Else save new 100ths second.
	EXX
TIM35:	CALL	GETCH	; Strip spaces etc.
	CALL	UC	; Upper case next character.
	CP	"A"	; am. indicator ?
	JR	Z,TIM40	; Go if yes, NC => am.
	CP	"P"	; pm. indicator ?
	SCF
	JR	Z,TIM40	; Go if yes, C => pm.
	OR	A	; Else end of line ?
	EXX
	JR	Z,SETIME	; Set new time if yes.
	DEFB	#3E	; Else give error.
TIM70:	POP	AF
BADTIM:	LD	B,.ITIME
	JR	TIM60	; Print error & re-prompt.

TIM40:	PUSH	AF
	INC	HL
	CALL	GETCH
	JR	NZ,TIM70
	POP	AF
	EXX
	LD	B,#0C
	LD	A,H
	JR	C,TIM50
	CP	B
	JR	Z,TIM45
	JR	NC,BADTIM
	DEFB	#D2
TIM45:	LD	H,#00
	JR	SETIME

TIM50:	OR	A	; Hour=0 pm is invalid.
	JR	Z,BADTIM
	CP	B	; Convert to 24 hour hours.
	JR	NC,TIM55	;   (no change if >12)
	ADD	A,B
TIM55:	LD	H,A	; H=new hours.
SETIME:	LD	C,_STIME
	CALL	BDOS	; Attempt to set the new time.
	AND	.ITIME	; 0 => OK, else .ITIME => invalid time.
	RET	Z	; Return if no error.
	LD	B,A	; B=error code.
TIM60:	LD	DE,ENVNAME	; Get message into BUFF2.
	LD	C,_EXPLAIN
	CALL	BDOS
	PUSH	DE	; Save message ptr.
	CALL	LPRINT	; New line & '***'.
	LD	A,#0D
	CALL	DMESS
	POP	DE
	CALL	PRTSTR	; Print actual message.
	LD	A,#0E	; Followed by message after error.
	CALL	DMESSCR
	JP	NEWTIM	; Prompt & input for another date.

		SUBTTL	VER
;       The VER command simply prints the version number.
@VER:	AND	(HL)
	LD	A,.INP	; Error if any parameters.
	RET	NZ
	LD	HL,#4039	; Read address of KBDOS's version
	CALL	_RDSLT	;   message.
	PUSH	AF
	DEC	HL
	CALL	_RDSLT
	POP	HL
	LD	L,A	; HL -> message in KBDOS ROM.
	SCF	; Skip printing first time round.
VER10:	CALL	NC,PRCHAR	; Print character from message.
	CALL	_RDSLT	; Read a character from the message.
	INC	HL
	OR	A
	JR	NZ,VER10	; Go with character and NC if not end.
	CALL	LPRINT
	LD	HL,(#01)	; Get pointer to MSXDOS.SYS's message.
	LD	DE,#30
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)	; DE -> message.
	CALL	DMSCR	; Print message and CRLF.
	LD	DE,VERMSG	; Finally print COMMAND.COM's message.
	JP	DMSCR

_RDSLT:	LD	A,(#F348)
RDSLOT:	EX	DE,HL
	PUSH	DE
	LD	HL,#00
	ADD	HL,SP
	LD	SP,#F51F
	PUSH	HL
	EX	DE,HL
	CALL	RDSLT
	POP	HL
	LD	SP,HL
	POP	HL
	RET

VERMSG:	DEFB	"COMMAND2.COM version 2.41",13,10
	DEFB	"Copyright (c) 1995-1997 by C.P.U.",13,10,0

		SUBTTL	VERIFY
;******************************************************************************
;        This  is  the  VERIFY  command   routine.   It   simply   sets   disk
; verify-after-write ON or OFF.
@VERIFY:	AND	(HL)
	JR	NZ,SETVFY	; Go & set verify if parameters given.
	LD	C,_GETVFY	; Else get & print verify state.
	CALL	BDOS
	LD	HL,OFFWORD$+1	; Assume disabled.
	INC	B
	DEC	B	; 0 => disabled, else enabled.
	JR	Z,GOTVFY
	LD	HL,ONWORD$+1
GOTVFY:	LD	A,#28	; Print 'VERIFY='.
	CALL	DMESS
	EX	DE,HL	; DE -> ON/OFF string.
	JP	DMSCR	; Print verify state.

SETVFY:	EX	DE,HL	; DE -> parameter.
	DEC	DE	; Pretend DE -> length byte.
	LD	HL,ONWORD$	; Check for ON.
	LD	B,(HL)	; Length of 'ON'.
	LD	C,#FF	; NZ => ON.
	CALL	COMPARE
	JR	NC,VFY10
	INC	B	; Ready for OFF check.
	INC	C	; 0 => OFF.
	INC	HL	; Point passed null at end of ON.
	CALL	C,COMPARE	; Check for OFF if not ON.
	LD	A,.IPARM	; 'Invalid parameter' if not ON or OFF.
	RET	C
VFY10:	INC	DE
	DJNZ	VFY10
	INC	DE
	EX	DE,HL
	LD	A,(HL)
	CALL	SEP?
	LD	A,.IPARM
	RET	NZ
	CALL	GETCH
	LD	A,.INP
	RET	NZ
	LD	E,C
	LD	C,_VERIFY
	JP	BDOS

@DSKCHK:	AND	(HL)
	JR	NZ,DSK20
	LD	C,_DSKCHK
	XOR	A
	CALL	BDOS
	LD	HL,ONWORD$+1
	INC	B
	DEC	B
	JR	Z,DSK10
	LD	HL,OFFWORD$+1
DSK10:	LD	A,#47
	CALL	DMESS
	EX	DE,HL
	JP	DMSCR

DSK20:	EX	DE,HL
	DEC	DE
	LD	HL,ONWORD$
	LD	B,(HL)
	LD	C,#00
	CALL	COMPARE
	JR	NC,DSK30
	INC	B
	DEC	C
	INC	HL
	CALL	C,COMPARE
	LD	A,.IPARM
	RET	C
DSK30:	INC	DE
	DJNZ	DSK30
	INC	DE
	EX	DE,HL
	LD	A,(HL)
	CALL	SEP?
	LD	A,.IPARM
	RET	NZ
	CALL	GETCH
	LD	A,.INP
	RET	NZ
	LD	B,C
	LD	A,#01
	LD	C,_DSKCHK
	JP	BDOS

