	name('copy')
	TITLE	MSX-DOS 2 - COMMAND2.COM
	SUBTTL	HELP, CONCAT, COPY and TYPE commands
	INCLUDE	command.inc
;******************************************************************************
;
;        The COPY, CONCAT, TYPE and HELP commands and their shared file
; copying engine.
;
;        Based on COMMAND.COM 2.31, copyright (1986) IS Systems Ltd, and on
; the COMMAND2.COM 2.40/2.41 additions by Fokke Post, whose source code was
; released as freeware in 2003.
;
;******************************************************************************
@COPY::	LD	DE,CPYOPTS
	CALL	PARSE##
	CALL	Z,CHKPAR##
	CALL	Z,PRSDEST
	RET	NZ
	LD	(IY+#18),B
	EX	DE,HL
	LD	(DESTADDR##),HL
	LD	HL,OPTFLAG2##
	BIT	5,(HL)
	JR	NZ,COP10
	SET	6,(HL)
COP10:	SET	7,(HL)
	LD	A,(HL)
	LD	HL,OPTFLAG1##
	LD	B,(HL)
	LD	(HL),A
	LD	L,E
	LD	H,D
	CALL	GETCH##
	CALL	CHKOPT##
	RET	NZ
	CALL	GETCH##
	LD	A,.INP##
	RET	NZ
	LD	HL,OPTFLAG1##
	LD	A,(HL)
	LD	(OPTFLAG4##),A
	AND	#DF
	OR	B
	LD	(HL),A
	XOR	A
	LD	(DE),A
	LD	(FIB3##+#0E),A
	LD	(FIB2##),A
	LD	(IY+#15),#FF
	LD	L,A
	LD	H,A
	LD	(CNTFILE##),HL
	LD	(UNKNOWN2##),HL
	CALL	FIRST##
	RET	C
	RES	0,(IY+#06)
	CALL	CPYFORK
	RET	NZ
	LD	C,_GETVFY##
	CALL	BDOS
	LD	(IY+#16),B
	LD	DE,ABORT
	PUSH	DE
	LD	C,_DEFAB##
	CALL	BDOS
	RET	NZ
	LD	HL,OPTFLAG3##
	LD	A,(HL)
	XOR	#01
	LD	(HL),A
	BIT	3,(HL)
	JR	Z,NCPYV
	LD	E,#FF
	LD	C,_VERIFY##
	CALL	BDOS
NCPYV:	LD	DE,ENVDATA##	; Start of buffer.
	EXX	; Save current buffer address in DE'.
OPCPY:	LD	DE,FIB1##	; Attempt to open source file.
	LD	C,_OPEN##
	LD	A,#01	; Not write.
	CALL	BDOS
	JR	Z,OPC10	; Go if opened OK.
	CALL	CPYWRT	; Make sure all source files written.
	EXX	; Save new start of buffer.
	LD	B,(IY+#17)	; If no error do a 'join' to
	LD	C,_JOIN##	;   close all open files.
	CALL	Z,BDOS
	CALL	Z,CPYFORK	; Then 'fork' again for next time.
	RET	NZ
	LD	DE,FIB1##	; Attempt to open source again.
	LD	C,_OPEN##
	LD	A,#01	; Not write.
	CALL	BDOS
	RET	NZ	; This time return errors.
OPC10:	LD	A,B	; Get source file handle.
	LD	(TYPHNDL##),A	; Save this source file handle.
	EXX	; DE -> current buffer position.
	LD	HL,(EXITADDR##)	; Make sure there is enough memory for
	OR	A	;   source file info. Also allow some
	SBC	HL,DE	;   extra for efficiency (see comments
	LD	BC,#0800	;   at start of COPY).
	SBC	HL,BC
	JR	NC,MEMOK	; Go if enough memory.
	CALL	CPYWRT	; Else write out source files read so
	RET	NZ	;   far.
MEMOK:	LD	HL,(UNKNOWN2##)	; Add info about new source file onto
	LD	B,(IY+#14)	; Get source handle.
CONTRD:	LD	(UNKNOWN2##),DE
	LD	A,H
	OR	L
	JR	Z,NLF
	LD	(HL),E
	INC	HL
	LD	(HL),D
NLF:	EX	DE,HL	; HL -> current buffer position.
	LD	(HL),#00	; End of chain.
	INC	HL
	LD	(HL),#00
	INC	HL
	LD	DE,FIB1##+1	; Remember source filename.
NLF10:	LD	A,(DE)
	LD	(HL),A
	INC	HL
	INC	DE
	OR	A
	JR	NZ,NLF10
	LD	(HL),B	; Save file handle / FF => continue.
	INC	HL
	EX	DE,HL	; DE -> buffer.
	LD	HL,FIB1##+#11	; Copy date from FIB.
	LDI
	LDI
	LD	HL,FIB1##+#0F	; Copy time from FIB.
	LDI
	LDI
	LD	HL,#0203	; Round up to next sector boundary (&
	ADD	HL,DE	;   allow 4 bytes for start & end ptr).
	LD	L,#00
	RES	0,H
	EX	DE,HL	; HL -> buffer, DE -> data start.
	LD	(HL),E	; Save data start.
	INC	HL
	LD	(HL),D
	INC	HL
	PUSH	HL	; Save ptr to end of data pointer.
	CALL	READ	; Read from file, DE updated.
	POP	HL	; Get old buffer address.
	RET	NZ	; Ret if error from read.
	CALL	C,SETEOF	; Add ^Z on end if /A on destination.
	LD	(HL),E	; Save the end address of the data read
	INC	HL	;   (Cy still not corrupted)
	LD	(HL),D
	JR	C,NXTCPY	; Read next file if buffer not full.
	CALL	CPYWRT	; Write out source files read.
	RET	NZ
	OR	A	; Read next source if unable to create
	JR	NZ,NXTCPY	;   last destination.
	LD	B,#FF	; Read more from the start of buffer.
	JR	CONTRD

NXTCPY:	EXX
	CALL	NEXT##
	JP	NC,OPCPY
	CALL	Z,CPYWRT
	RET	NZ
	BIT	5,(IY+#0A)
	RET	Z
	LD	A,#2E
	CALL	DMESS##
	LD	HL,(CNTFILE##)
	PUSH	HL
	LD	IX,XBUF1##
	PUSH	IX
	CALL	D16##
	POP	DE
	CALL	PRTSTR##
	POP	HL
	DEC	HL
	LD	A,H
	OR	L
	LD	A,#2F
	JR	Z,CPSING
	LD	A,#30
CPSING:	JP	DMESSCR##

CPYWRT:	LD	HL,(UNKNOWN2##)
	LD	A,H
	OR	L
	JP	Z,WRET
	LD	HL,ENVDATA##
CW10:	LD	C,(HL)	; Get ptr to next source file.
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,L	; Save ptr to source filename in DE.
	LD	D,H
FNDEND:	LD	A,(HL)	; Find end of name string.
	INC	HL
	OR	A
	JR	NZ,FNDEND
	LD	A,(HL)	; File handle = FF => continue write.
	INC	A
	JP	Z,CONTWRT
	EXX	; Save HL, DE and BC.
	LD	B,(IY+#15)	; Close existing destination
	LD	(IY+#15),#FF	;   handle to guarantee that
	LD	C,_CLOSE##	;   there's a spare handle.
	CALL	BDOS	;   (error ignored)
	LD	DE,(DESTADDR##)	; DE -> destination filename.
	BIT	5,(IY+#18)
	JR	NZ,CRTDST	; Just attempt a create if yes.
	LD	HL,(CNTFILE##)	; First file been created ?
	LD	A,H
	OR	L
	JR	NZ,DIRDEST	; Go & create in directory if yes.
	CALL	CPYCRT	; Attempt to create dest (DE -> name).
	CP	.DIRX##	; Attempting to create in a directory ?
	JR	NZ,DONDEST	; Go with error code if not.
	LD	HL,FIB2##	; Save FIB for sub-directory for
	LD	DE,FIB3##	;   creating dest files in it.
	LD	BC,#40
	LDIR
	JR	INDIR	; Create destination in directory.

DIRDEST:	LD	A,(FIB2##+#0E)	; OK if last dest was a device
	AND	#80	;   or directory, else 'Cannot
	JR	NZ,CRTDST	;   overwrite previous dest.'.
	LD	A,(FIB3##+#0E)	; Give error if first dest was
	AND	#10	;   not a directory.
	LD	A,.OVDEST##
	JR	Z,BADEST	;   (same dest as first file).
INDIR:	LD	DE,FIB3##
CRTDST:	CALL	CPYCRT
DONDEST:	OR	A	; A=error from create attempt.
	JR	Z,DESTOK	; Go if dest created OK.
	PUSH	AF	; Else open a file as a dummy dest to
	CALL	NZ,OPNUL	;   ensure there's always a dest open.
	POP	AF
	CP	.FOPEN##	; If .FOPEN, then check for 'file
	JR	NZ,BADEST	;   cannot be copied onto itself'.
	EXX
	LD	A,(HL)	; Get source handle.
	EXX
	LD	B,A
	LD	DE,FIB2##	; See if source & attempted destination
	LD	C,_HTEST##	;   file are the same.
	CALL	BDOS
	JR	NZ,BADEST
	OR	B
	LD	A,.COPY##	; 'File cannot be copied onto itself'
	JR	NZ,BADEST	;   if they are.
	LD	A,.BADEST##	; Else 'Cannot create destination'.
BADEST:	EXX
	PUSH	BC	; Save pointer to next source file.
	LD	C,A	; C=error code, DE -> source filename.
	XOR	A
	LD	(FIB2##),A	; No dest created (for abort routine).
	PUSH	DE
	LD	DE,FIB2##+1	; Print destination filename
	CALL	DBADF##	; Print filename & error message.
	POP	DE
	POP	HL	; HL -> next source file.
	INC	A	; A<>0 => couldn't create destination.
	JR	WRNXT	; Attempt to write next source file.

DESTOK:	EXX	; Print name of this source file if
	PUSH	DE	;   ambiguous source specified.
	EXX
	POP	DE
	BIT	5,(IY+#0A)
	CALL	NZ,DMSCR##
	LD	HL,(CNTFILE##)	; Inc count of no. files copied.
	INC	HL
	LD	(CNTFILE##),HL
	LD	DE,FIB2##	; Attempt to open new file.
	LD	A,#02	; Not read.
	LD	C,_OPEN##
	CALL	BDOS
	RET	NZ
	LD	(IY+#15),B	; Save destination file handle.
	EXX
CONTWRT:	PUSH	BC
	INC	HL	; Skip source file handle.
	LD	DE,FILEDATE##	; Save date of source in SDATE.
	LDI
	LDI
	LD	DE,FILETIME##	; Save time of source in STIME.
	LDI
	LDI
	LD	E,(HL)	; Get start address of data.
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,(HL)	; Get end address of data.
	INC	HL
	LD	H,(HL)
	LD	L,A
	EX	DE,HL	; HL=start, DE=end.
	CALL	WRITE2	; Attempt to write the data.
	POP	HL	; Get pointer to next source file.
	RET	NZ	; Ret if error from write.
WRNXT:	LD	C,A	; A<>0 => couldn't create destination.
	LD	A,H
	OR	L
	JP	NZ,CW10	; Go if more source files to do.
	LD	(UNKNOWN2##),HL
	LD	A,C	; A<>0 => last dest not created.
WRET:	LD	DE,ENVDATA##	; Else start again at start of buffer.
	RET

;        This routine is used by COPY to do a  'fork'  before  opening  source
; files.  This  allows  it to later do a 'join' as a convenient way of closing
; all files, which needs to be done when it runs out of file handles to use.
;        A destination file is always open to 'reserve' a  handle.  After  the
; fork  here  it  is  a  dummy destination open to the NUL device, but after a
; destination has been created for the first time this will be replaced by the
; previous destinatin file.
; On exit, AF is an error code.
CPYFORK:	LD	C,_FORK##	; Do a 'fork' so that all files can be
	CALL	BDOS	;   closed by doing a 'join'.
	RET	NZ
	LD	A,B
	LD	(COPYID##),A	; Save returned id for doing a join.
OPNUL:	LD	DE,NULDEV	; Open a dummy handle to the NUL device
	LD	C,_OPEN##	;   to 'reserve' a handle for the
	LD	A,#03	;   destination file.
	CALL	BDOS
	RET	NZ
	LD	(IY+#15),B	; Save destination handle.
	RET

SETEOF:	BIT	5,(IY+#06)
	RET	Z	;   /A on destination.
	LD	A,#1A
	LD	(DE),A
	INC	DE
	RET

;        This routine is called by the  COPY  command  to  simply  create  the
; destination file, and return with the error code. On entry, DE points to the
; filename or FIB. Before doing the 'find  new',  HL  is  pointed  to  a  null
; filename.  This  is  done  in case DE points to a FIB, in which case HL must
; point to a filename. A null filename is equivalent to *.*, which  means  use
; the 'template' filename in the new FIB. This needs to  be  copied  from  the
; source filename for both kinds of 'find new'.
CPYCRT:	EXX
	PUSH	DE	; Get pointer to source filename.
	EXX
	POP	BC
	LD	HL,FIB2##+1	; Copy source to here.
CPYSRCE:	LD	A,(BC)
	LD	(HL),A
	INC	HL
	INC	BC
	OR	A
	JR	NZ,CPYSRCE
	LD	HL,NULDEV+3	; HL->null filename, in case DE->FIB.
	LD	IX,FIB2##	; FIB for dest goes here.
	LD	BC,_FNEW##	; Zero attributes.
	JP	BDOS

NULDEV:	DEFB	"NUL",0	; Name of NUL device for dummy dest.

@HELP::	CALL	SETP##
	LD	A,(HL)
	OR	A
	LD	A,#31
	JP	Z,DMESSCR##
	PUSH	HL
	EXX
	POP	DE
	LD	BC,_PARSE##
	CALL	BDOS
	RET	NZ
	EX	DE,HL
	LD	A,(HL)
	CALL	SEP?##
	LD	A,.NOHELP##
	CALL	Z,GCHKEOL##
	RET	NZ
	LD	(HL),A
	LD	HL,HELP$##
	CALL	GENV2##
	RET	NZ
	LD	A,(DE)
	OR	A
	JR	NZ,GOTSTR
	LD	HL,DHELP$##
	PUSH	DE
	CALL	NCOPY##
	POP	DE
GOTSTR:	LD	B,#00	; Parse source of HELP files.
	LD	C,_PARSE##
	PUSH	DE
	CALL	BDOS
	EX	DE,HL	; HL -> terminating character.
	POP	DE	; DE -> start of string.
	RET	NZ
	LD	A,B	; Add a '\' if non-null last item.
	AND	#18
	JR	Z,GOT150
	LD	(HL),"\"
	INC	HL
GOT150:	EXX	; Get pointer to command for HELP.
	PUSH	HL
	EXX
	POP	BC	; BC -> start of command name for HELP.
CPYHLP:	LD	A,(BC)	; Copy command name to end of HELP
	LD	(HL),A	;   path.
	INC	BC
	INC	HL
	OR	A
	JR	NZ,CPYHLP
	DEC	HL	; Stick a '.HLP' extension on the end.
	LD	(HL),"."
	INC	HL
	LD	(HL),"H"
	INC	HL
	LD	(HL),"L"
	INC	HL
	LD	(HL),"P"
	INC	HL
	LD	(HL),A	; Terminate in a null.
	EX	DE,HL	; HL -> start of HELP drive/path/file.
	LD	DE,HLPOPTS	; DE -> table of options for HELP.
	CALL	TYPFIL	; TYPE the help file (NC, A=0).
	OR	A
	RET	Z
	CP	.IDRV##	; Convert certain errors into 'File for
	JR	Z,NOHELP	;   HELP not found'.
	CP	.IPATH##
	JR	Z,NOHELP
	CP	.NODIR##
	JR	Z,NOHELP
	CP	.NOFIL##
	RET	NZ
NOHELP:	LD	A,.NOHELP##
	RET

@TYPE::	LD	DE,TYPOPTS
TYPFIL:	PUSH	AF	; Save HELP/TYPE flag (NZ => TYPE).
	CALL	PARSE##	; Parse source filename.
	CALL	Z,CHKPAR##	; Check that something was parsed.
	CALL	Z,CHKEOL##	; Check for garbage on the end of line.
	POP	BC	; B=NZ => TYPE, not HELP.
	RET	NZ
	LD	HL,OPTFLAG2##	; If /B not given, then default to /A.
	OR	B	; If HELP, then check that the
	JR	NZ,TYP10	;   parameter was not ambiguous.
	BIT	5,(IY+#0A)
	JR	NZ,NOHELP
TYP10:	BIT	6,(HL)
	JR	NZ,TYP20
	SET	5,(HL)
TYP20:	SET	7,(HL)
	CALL	FIRST##	; Look for first file.
	RET	C
	SET	0,(IY+#06)
TYP30:	BIT	5,(IY+#0A)
	JR	Z,NAMBIG	;   ambiguous source filename.
	LD	DE,FIB1##+1	; Print source filename.
	PUSH	DE
	CALL	DMSCR##
	POP	DE
UND:	LD	A,(DE)	; Underline it with hyphens.
	OR	A
	JR	Z,UNDD
	INC	DE
	LD	A,"-"
	CALL	PRCHAR##
	JR	UND

UNDD:	CALL	LPRINT##
NAMBIG:	LD	DE,FIB1##	; Attempt to open source file.
	LD	BC,_OPEN##
	LD	A,#01	; Not write.
	CALL	BDOS
	RET	NZ
	LD	(IY+#14),B	; Save source file handle.
RDTYP:	LD	DE,ENVDATA##+#EB	; Start of buffer.
	CALL	READ	; Read from source file into buffer,
	RET	NZ	;   and print on screen.
	JR	NC,RDTYP	; Keep going if not end of file.
	CALL	LPRINT##	; Else put a CR, LF on the end.
	LD	C,_CLOSE##	; End of file reached, so close it &
	LD	B,(IY+#14)	;   look for next.
	CALL	BDOS
	RET	NZ	; Return if error, else Z.
	CALL	NEXT##	; Look for next source file.
	JR	NC,TYP30	; Open & read next if found.
	RET	; Ret with error code from NEXT.

		SUBTTL	CONCAT
;******************************************************************************
;        This is the CONCAT command routine. This takes  a  possibly  ambigous
; source  filespec  and  an unambiguous destination filename, and concatenates
; all the source files into  the  destination  files.  CONCAT  shares  several
; routines with copy, and behaves in a similar way for reading source files.
@CONCAT::	LD	DE,VOPTS	; DE -> table of valid / options.
	CALL	PARSE##	; Parse source filename.
	CALL	Z,CHKPAR##	; Check that something was parsed.
	CALL	Z,PRSDEST	; Parse destination filename.
	RET	NZ	; Ret if error, else DE -> dest.
	LD	A,B	; Get parse flags for destination.
	AND	#05	; 'Missing parameter' if nothing
	LD	A,.NOPAR##	;   parsed.
	RET	Z
	EX	DE,HL	; DE -> terminating character.
	LD	(DESTADDR##),HL	; Save pointer to destination string.
	LD	HL,OPTFLAG2##	; If /B not given at start, then set /A
	BIT	6,(HL)
	JR	NZ,CON40
	SET	5,(HL)
CON40:	SET	7,(HL)
	LD	A,(HL)
	LD	HL,OPTFLAG1##
	LD	B,(HL)	; Save ATTRS & initialise it to parse
	LD	(HL),A	;   destination options into it.
	LD	L,E	; Point HL to terminating character.
	LD	H,D
	CALL	GETCH##
	CALL	CHKOPT##
	RET	NZ
	CALL	GETCH##	; Skip separators & give error if not
	LD	A,.INP##	;   end of line.
	RET	NZ
	LD	HL,OPTFLAG1##
	LD	A,(HL)	; Get destination / options.
	LD	(OPTFLAG4##),A	; Save in DESTOPT.
	AND	#BF	; Mask out destination / B option.
	OR	B	; Combine destination & source options.
	LD	(HL),A	; Restore original ATTRS.
	XOR	A	; Ensure dest. is null-terminated.
	LD	(DE),A
	LD	(FIB2##),A	; No destination created yet.
	LD	(IY+#15),#FF	; No destination openned yet.
	CALL	FIRST##	; Make sure at least one file exists !
	RET	C
	LD	C,_GETVFY##	; Save current verify state in case /V.
	CALL	BDOS
	LD	(IY+#16),B
	LD	DE,(DESTADDR##)	; Attempt to create destination file.
	LD	BC,_FNEW##	; Do a 'Find New' and 'Open' rather
	LD	IX,FIB2##	;   than a 'create' so that ABORT
	CALL	BDOS	;   routine still works.
	RET	NZ
	LD	DE,ABORT	; Define abort routine to tidy up if an
	PUSH	DE	;   abort occurs (eg. deletes dest if
	LD	C,_DEFAB##	;   it has not been closed yet). Also
	CALL	BDOS	;   returns via here when command
	RET	NZ	;   finishes with or without error.
	LD	DE,FIB2##	; Attempt to open the new dest file.
	LD	A,#02	; Not read.
	LD	C,_OPEN##
	CALL	BDOS
	RET	NZ
	LD	(IY+#15),B	; Save handle of destination file.
	BIT	3,(IY+#05)
	JR	Z,NCATV
	LD	E,#FF	; FF => verify enabled.
	LD	C,_VERIFY##
	CALL	BDOS
NCATV:	LD	DE,ENVNAME##-#14
OPCAT:	EXX	; Get another buffer full.
	LD	DE,FIB1##	; Check to see if the found source file
	LD	B,(IY+#15)	;   is in fact the destination file,
	LD	C,_HTEST##	;   and print the filename and a
	CALL	BDOS	;   message if it is.
	RET	NZ
	OR	B	; Z => different files (OK).
	LD	A,.NOCAT##
	JR	NZ,NXTCAT	; Go with NZ, A=error if the same file.
	BIT	5,(IY+#0A)
	LD	DE,FIB1##+1	;   ambiguous source specified.
	CALL	NZ,DMSCR##
	LD	DE,FIB1##	; Attempt to open source file.
	LD	C,_OPEN##
	LD	A,#01	; Not write.
	CALL	BDOS
	RET	NZ
	LD	(IY+#14),B	; Save source file handle.
	EXX	; DE -> current buffer position.
RDCAT:	CALL	READ	; Read from source file into buffer.
	RET	NZ
	JR	C,GOTEOF	; Go if end of source file reached.
	CALL	WRITE	; Else write out entire buffer to dest.
	RET	NZ	; DE -> back to buffer start.
	JR	RDCAT	; Continue reading.

GOTEOF:	EXX	; Save buffer ptr in DE'.
	LD	C,_CLOSE##	; End of file reached, so close it &
	LD	B,(IY+#14)	;   look for next.
	CALL	BDOS
	RET	NZ	; Return if error, else Z.
NXTCAT:	CALL	NZ,DBADFIL##	; Print fn. & msg. if not from above.
	CALL	NEXT##	; Look for next source file.
	EXX	; DE -> current buffer position.
	JR	NC,OPCAT	; Open & read next if found.
	CALL	Z,WRITE	; Write out remaining stuff in buffer.
	RET	NZ	; Ret if error.
	BIT	6,(IY+#06)
	RET	NZ	;   on destination.
	LD	HL,ENVDATA##	; Else write a ^Z on the end.
	LD	(HL),#1A
	EX	DE,HL
	LD	HL,#01
	LD	C,_WRITE##
	LD	B,(IY+#15)
	JP	BDOS

CPYOPTS:	DEFB	"T"
	DEFB	#01
VOPTS:	DEFB	"V"
	DEFB	#08
TYPOPTS:	DEFB	"A"
	DEFB	#20
	DEFB	"B"
	DEFB	#40
	DEFB	"H"
	DEFB	#02
	DEFB	"P"
	DEFB	#00
	DEFB	"S"
	DEFB	#04
HLPOPTS:	DEFB	0	; No / options for HELP.

;        This routine is called from COPY, CONCAT, TYPE  and  HELP  and  reads
; data from the source file.
;        After reading a buffer full, it performs any processing necessary  on
; the  file for ASCII copies (ie. truncating the file at the first ^Z) and for
; the TYPE command (ie.  converting  non-printable  characters  into  printing
; characters).   These checks should really be done by calling the CHKCHR BDOS
; function to allow for 16-bit characters, but this is far too slow (about 1/2
; minute for 40K), so these  characters  are  searched  for  byte-by-byte.  In
; practise  this  will  not  matter  because  16-bit characters do not contain
; control characters.
; On entry, DE -> current buffer address.
; On exit, DE -> updated buffer address.
;          AF = error code.
;          AF = Z, NC => read OK, buffer full (not end of file).
;          AF = Z, Cy => read OK, end of source file read (or ^Z in /A mode).
;       The entry point is not at the top, but at READ.
HLP10:	EX	DE,HL	; HL -> next free byte in buffer.
	LD	A,H	; No bytes read = 0 (end of file) ?
	OR	L
	SCF	; Return C => end of file if yes.
	RET	Z	; Z => no error.
	PUSH	IX	; If fewer bytes were read than
	POP	BC	;   requested, then read some more.
	XOR	A	; Z => no error, NC.
	SBC	HL,BC
	RET	Z	; Z => no error, NC => buffer full.
READ:	LD	HL,(EXITADDR##)	; Get top of memory, & allow an extra
	DEC	HL	;   byte for COPY /A to add ^Z on end.
	XOR	A	; NC, no error.
	SBC	HL,DE	; Calculate size left (ie. max. no.
	LD	L,A	;   bytes to read) but truncate to a
	RES	0,H	;   multiple of the sector size for
	RET	Z	;   efficiency. Ret if buffer full.
	BIT	0,(IY+#06)
	JR	Z,NLIMIT
	LD	BC,#1800	; Limit to 6K if TYPE (this prevents it
	SBC	HL,BC	;   from sitting there trying to read
	ADD	HL,BC	;   Ks & Ks of stuff when only the
	JR	C,NLIMIT	;   start of the file is really wanted)
	LD	H,B
NLIMIT:	PUSH	DE	; Save ptr to start of buffer.
	PUSH	HL	; Save no. bytes requested.
	PUSH	HL
	POP	IX	; Save in IX too.
	LD	C,_READ##
	LD	B,(IY+#14)
	CALL	BDOS
	POP	BC	; Get no. bytes requested.
	POP	DE	; Restore ptr. to start of buffer.
	JR	Z,NRDER	; Go if no error from read.
	CP	.EOF##	; Ignore end of file (no. bytes read=0
	RET	NZ	;   in this case), but return others.
NRDER:	EX	DE,HL	; HL -> start, DE = no. bytes read.
	ADD	HL,DE	; HL = next free byte.
	BIT	0,(IY+#06)
	JR	NZ,CHKCHRS	; Go if yes.
	BIT	5,(IY+#03)
	JR	Z,HLP10	; Go if not.
CHKCHRS:	SBC	HL,DE	; Point HL back to start.
	LD	C,E	; BC=down counter for bytes in buffer.
	LD	B,D
	LD	DE,#00	; DE = no. bytes checked so far.
	JR	CHK20

CHKN:	INC	HL	; Next character.
	INC	DE
	DEC	BC	; Decrement character count.
CHK20:	LD	A,B	; All characters checked ?
	OR	C
	JR	Z,HLP10	; Go if yes.
	LD	A,(HL)	; Get character.
	BIT	5,(IY+#03)
	JR	Z,CHK30	; Skip check if not.
	EX	DE,HL	; DE -> next free byte in buffer.
	SUB	#1A	; End of file in ASCII mode ?
	SCF
	RET	Z	; Ret with Z => no error, C => EOF.
	EX	DE,HL	; Restore pointers.
	LD	A,(HL)	; Get character again.
CHK30:	BIT	0,(IY+#06)
	JR	Z,CHKN	;   printing characters.
	BIT	5,(IY+#03)
	JR	Z,PRCH
	CP	#7F
	JR	Z,PRCC
	CP	#20	; TYPE, so convert control characters
	JR	NC,PRCH	;   into printing characters.
	CP	#0D	; Not CR or LF though !
	JR	Z,PRCH
	CP	#0A
	JR	Z,PRCH
	CP	#09
	JR	Z,PRCH
PRCC:	XOR	#40
	PUSH	AF
	LD	A,"^"
	CALL	PRCHAR##
	POP	AF
PRCH:	CALL	PRCHAR##	; Output directly if TYPE.
	JR	CHKN	; Check next character.

WRITE:	LD	HL,ENVNAME##-#14
WRITE2:	PUSH	HL
	EX	DE,HL
	OR	A
	SBC	HL,DE
	LD	B,(IY+#15)
	LD	C,_WRITE##
	PUSH	BC
	CALL	BDOS
	POP	BC
	JR	NZ,WRERR
	BIT	0,(IY+#05)
	JR	Z,NSURE
	LD	IX,(FILETIME##)
	LD	HL,(FILEDATE##)
	LD	A,#01
	LD	C,_HFTIME##
	PUSH	BC
	CALL	BDOS
	POP	BC
NSURE:	LD	C,_ENSURE##	; Ensure & flush buffers.
	CALL	Z,BDOS
WRERR:	POP	DE	; Return DE -> start of buffer.
	RET	; With error code.

;        This routine is jumped to after  CONCAT  and  COPY  finish.  This  is
; either  because an abort error occured, or just because the command returned
; successfully or with an error. In both cases, the destination file handle is
; closed and then the destination file is deleted if A<>0.
ABORT:	LD	DE,CLI_ABORT##	; Stop recursion if another abort.
	PUSH	DE	; Also return to here.
	PUSH	BC	; Save secondary error in case abort.
	PUSH	AF	; Save error code from CONCAT or COPY.
	LD	C,_DEFAB##
	CALL	BDOS	;   (error ignored)
	LD	E,(IY+#16)	; Restore the saved verify state.
	LD	C,_VERIFY##
	CALL	BDOS
	LD	B,(IY+#15)	; Close the destination file.
	LD	C,_CLOSE##
	CALL	BDOS	;   (error ignored)
	POP	AF	; Get back error code.
	PUSH	AF	; Delete the possibly partial
	LD	DE,FIB2##	;   destination file if error.
	LD	C,_DELETE##
	OR	A
	JR	Z,NODEL
	CP	.ABORT##
NODEL:	CALL	NZ,BDOS
	POP	AF
	POP	BC	; Get possible secondary error code.
	RET	; Return with command's error.

		SUBTTL	PRS##
;------------------------------------------------------------------------------
;        This little routine is called from  COPY  and  CONCAT  to  parse  the
; destination filename.
PRSDEST:	LD	B,#00	; Not parsing a valume name.
	LD	C,_PARSE##
	EX	DE,HL	; DE -> start of string.
	PUSH	DE
	CALL	BDOS
	EX	DE,HL	; HL -> terminating character.
	POP	DE	; DE -> start of filename string.
	RET	NZ	; Return if error.
	PUSH	HL
	CALL	GETCH##
	POP	HL
	JR	Z,TERMOK	; End of line is OK.
	CP	"/"	; / is OK as path string terminator.
	JR	Z,TERMOK
	LD	A,.IPATH##	; 'Invalid pathname' if terminator is
	RET	;   not a separator.

TERMOK:	LD	A,B	; Set ambiguous bit if null last item.
	AND	#18
	JR	NZ,TER10
	SET	5,B
TER10:	XOR	A	; Else no error.
	RET

