	TITLE	MSX-DOS 2 - COMMAND2.COM
	SUBTTL	Console I/O and mapper access
;******************************************************************************
;
;        Console and printer output, alias storage management, mapper
; segment access and keyboard input.
;
;        Based on COMMAND.COM 2.31, copyright (1986) IS Systems Ltd, and on
; the COMMAND2.COM 2.40/2.41 additions by Fokke Post, whose source code was
; released as freeware in 2003.
;
;******************************************************************************
DMESSCR:	CALL	GETMSG
DMSCR:	CALL	PRTSTR

LPRINT:	LD	A,#0D
	CALL	PRCHAR
	LD	A,#0A
PRCHAR:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	E,A
	LD	A,(ROWMAX)
	AND	A
	JR	Z,NPA10
	LD	A,E
	CP	#0D
	JR	NZ,OUCHNCR
	XOR	A
	LD	(COLCNT),A
	JR	NPA10

OUCHNCR:	CP	#0A
	JR	Z,OUCHPAU	; yes
	CP	#09	; tab?
	JR	NZ,OUCHK2	; no
	LD	A,(COLMAX)
	LD	D,A
	LD	A,(COLCNT)
	OR	#07
	INC	A
	LD	(COLCNT),A
	CP	D
	JR	C,NPA10
	LD	A,(COLCNT)
OUCHSUB:	SUB	D
	JR	NC,OUCHSUB
	ADD	A,D
	LD	(COLCNT),A
	JR	OUCHPAU

OUCHK2:	LD	A,(COLCNT)
	INC	A
	LD	(COLCNT),A
	LD	D,A
	LD	A,(COLMAX)
	CP	D
	JR	NZ,NPA10
	XOR	A
	LD	(COLCNT),A
OUCHPAU:	CALL	CONOUT
	CALL	CHKPAUSE
NPAUS:	XOR	A
	POP	BC
	POP	DE
	POP	HL
	RET

NPA10:	CALL	CONOUT
	JR	NPAUS

CHKPAUSE:	LD	A,(ROWMAX)
	DEC	A
	LD	(ROWMAX),A
	RET	NZ
	CALL	PAUSE
	CALL	SETP
	RET

CONOUT:	LD	C,_CONOUT
	JP	BDOS

SPACE?:	JP	NZ,PRCHAR
SPACE:	LD	A," "
	JP	PRCHAR

PRDIG2:	JR	Z,PRSPC2
PRD10:	LD	(IX),A
	INC	IX
	RET
PRSPC2:	LD	A," "
	JR	PRD10

SETP:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	BC,#014B	; Get the output height.
	LD	A,#04	;   (0 => 'infinite').
	CALL	BDOS
	LD	A,E	; Get width.
	LD	(COLMAX),A
	LD	A,D	; Get height.
	POP	BC
	POP	DE
	POP	HL
	RET	NZ	; Ignore it if error (shouldn't occur).
	DEC	A
	LD	(ROWMAX),A	; Save height in /P line count.
	RET

		SUBTTL  DMESS
DMESS:	CALL	GETMSG
PRTSTR:	LD	A,(DE)
	OR	A
	RET	Z	; Return if done.
	INC	DE
	CALL	PRCHAR	; Else output the character.
	JR	PRTSTR

GETMSG:	LD	B,A
	LD	DE,MESSAGES
	INC	B
MSG10:	DEC	B
	RET	Z	; Return with DE -> message if found.
MSG20:	LD	A,(DE)
	INC	DE
	OR	A
	JR	NZ,MSG20
	JR	MSG10

FNDALIAS:	PUSH	DE
	PUSH	HL
	CALL	SETPG2
	CALL	GETALIADDR
	SET	7,H
	BIT	7,B
	JR	Z,FND110
	LD	H,B
	LD	L,C
	JR	FND130

FND110:	LD	A,B
	OR	C
	JR	Z,FND130
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	DEC	HL
	ADD	HL,DE
	DEC	BC
	LD	A,D
	OR	E
	JR	NZ,FND110
FND120:	POP	HL
	LD	(HL),A
	POP	DE
	LD	(DE),A
	LD	B,A
	LD	C,A
	CALL	RSTPG2
	RET

FND130:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,D
	OR	E
	JR	Z,FND120
	POP	DE
	PUSH	DE
	CALL	NCOPY
	POP	BC
	POP	DE
	PUSH	DE
	PUSH	BC
	CALL	NCOPY
	LD	B,H
	LD	C,L
	POP	HL
	POP	DE
	CALL	RSTPG2
	RET

GETALIAS:	PUSH	DE
	PUSH	HL
	CALL	SETPG2
	CALL	GETALIADDR
	SET	7,H
GET60:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	POP	BC
	LD	A,D
	OR	E
	JR	Z,GET90
	PUSH	BC
	PUSH	HL
	CALL	STRCMP
	JR	Z,GET70
	POP	HL
	ADD	HL,DE
	DEC	HL
	DEC	HL
	JR	GET60

GET70:	POP	BC
	POP	BC
	POP	DE
	PUSH	DE
	CALL	NCOPY
GET80:	CALL	RSTPG2
	POP	DE
	RET

GET90:	POP	DE
	XOR	A
	LD	(DE),A
	PUSH	DE
	JR	GET80

SETALIAS:	PUSH	DE
	PUSH	HL
	CALL	SETPG2
	CALL	GETALIADDR
	SET	7,H
SET20:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	DEC	HL
	POP	BC
	LD	A,D
	OR	E
	EX	DE,HL
	PUSH	BC
	JR	Z,SET50
	EX	DE,HL
	PUSH	HL
	INC	HL
	INC	HL
	CALL	STRCMP
	JR	Z,SET30
	POP	HL
	ADD	HL,DE
	JR	SET20

SET30:	POP	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	DEC	HL
	LD	D,H
	LD	E,L
	ADD	HL,BC
SET40:	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	DEC	HL
	LD	A,B
	OR	C
	JR	Z,SET50
	LDIR
	JR	SET40

SET50:	LD	B,D
	LD	C,E
	POP	HL
	POP	DE
	LD	A,(DE)
	OR	A
	JR	Z,SET110
	PUSH	BC
	PUSH	DE
	LD	D,B
	LD	E,C
	INC	DE
	INC	DE
	LD	BC,#02
SET60:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	PUSH	HL
	LD	HL,(ALIEND)
	SET	7,H
	SBC	HL,DE
	POP	HL
	JR	Z,SET90
	INC	DE
	INC	BC
	OR	A
	JR	NZ,SET60
	POP	HL
SET70:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	BIT	6,D
	JR	NZ,SET100
	INC	DE
	INC	BC
	OR	A
	JR	NZ,SET70
	LD	(DE),A
	INC	DE
	LD	(DE),A
	POP	HL
	LD	(HL),C
	INC	HL
	LD	(HL),B
SET80:	CALL	RSTPG2
	RET

SET90:	POP	HL
SET100:	POP	HL
	CALL	RSTPG2
	LD	A,.NORAM
	OR	A
	RET

SET110:	LD	(BC),A
	INC	BC
	LD	(BC),A
	JR	SET80

SETLANG:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	EXX
	EX	AF,AF'
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	EX	AF,AF'
	EXX
	XOR	A
	LD	H,A
	LD	L,A
	ADD	HL,SP
	LD	SP,#F51F
	PUSH	HL
	LD	DE,#0402
	CALL	EXTBIO
	LD	(MAPADDR),HL
	LD	DE,#0401
	CALL	EXTBIO
	LD	(MAPTAB),HL
	LD	A,(EXPTBL)
	LD	HL,#2D
	CALL	RDSLT
	LD	(MSXVER),A
	POP	HL
	LD	SP,HL
	EXX
	EX	AF,AF'
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	EXX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

ALL_SEG:	PUSH	DE
	LD	DE,#00
	JR	XCAL

FRE_SEG:	PUSH	DE
	LD	DE,#03
	JR	XCAL

RD_SEG:	PUSH	DE
	LD	DE,#06
	JR	XCAL

WR_SEG:	PUSH	DE
	LD	DE,#09
	JR	XCAL

PUT_P2:	PUSH	DE
	LD	DE,#24
	JR	XCAL

GET_P2:	PUSH	DE
	LD	DE,#27
XCAL:	PUSH	HL
	LD	HL,(MAPADDR)
	ADD	HL,DE
	LD	(JMPADDR+1),HL
	POP	HL
	POP	DE
	PUSH	BC
	PUSH	HL
	PUSH	DE
	EXX
	LD	HL,#00
	ADD	HL,SP
	LD	SP,#F51F
	PUSH	HL
	EXX
JMPADDR:	CALL	#00
	POP	HL
	LD	SP,HL
	POP	DE
	LD	HL,#00
	LD	(JMPADDR+1),HL
	POP	HL
	POP	BC
	RET

SETPG2:	CALL	GET_P2
	LD	(TMPPAGE),A
	LD	A,(MAPPAGE)
	CALL	PUT_P2
	RET

RSTPG2:	LD	A,(TMPPAGE)
	CALL	PUT_P2
	RET

		SUBTTL  INCH
;******************************************************************************
;        This  routine  waits  for  a  key  to  be  pressed and then echos the
; character and prints a CR,LF, returning the character in L.  Before  reading
; the  character,  a  loop  is  entered  which  ensures that no characters are
; immediately waiting to be read, thus flushing the keyboard buffer first.
; On exit, C contains the character.
IC0:	LD	C,_INNOE	; Get character with no echo.
	CALL	BDOS
INCH:	LD	C,_CONST	; Console status.
	CALL	BDOS
	JR	NZ,IC0	; If key pressed, then read it.
	LD	C,_CONIN	; Wait for, read & echo another key.
	CALL	BDOS	; Character in L.
	JP	LPRINT

INLI:	LD	DE,ENVDATA
	LD	A,#7F
	LD	(DE),A
	LD	HL,EXPAND$
	CALL	OFF?
	SBC	A,A
	LD	C,_BUFIN
	CALL	Z,BDOS
	CALL	NZ,EDLINE
	CALL	LPRINT
	LD	HL,ENVDATA+1
	PUSH	HL
	LD	E,(HL)
	XOR	A
	LD	D,A
	ADD	HL,DE
	INC	HL
	LD	(HL),D
	POP	HL
	RET

