#!/usr/bin/env bash

set -e

PWD=$(pwd)

if [[ "$1" == "-s" ]]; then
  SRC_DIR=$2

  for file in "${@:3}"
  do
    sf "${SRC_DIR}/${file}"
  done

  exit 0
fi

SRC_FILE=$1
DEST_FILE=$2

PATTERN="\*"
if [[ "${SRC_FILE}" =~ $PATTERN ]]; then
  for file in ${PWD}/${SRC_FILE}
  do
    [ -e "$file" ] || continue
    target=$(basename "$file")
    src=${file#"$PWD/"}
    sf "$src" "${target,,}"
  done

  exit 0
fi

if [[ "${DEST_FILE}" == "" ]]; then
  DEST_FILE=$(basename $SRC_FILE)
fi

CURRENT_LINK=$(readlink ${PWD}/${WRK_DIR}/${DEST_FILE} || echo "NEWFILE")

if [[ "$CURRENT_LINK" == 'NEWFILE' ]]; then
  ln -s "${PWD}/$SRC_FILE" "${PWD}/${WRK_DIR}/${DEST_FILE}"
  exit 0
fi

if [[ "$CURRENT_LINK" != "${PWD}/$SRC_FILE" ]]; then
  echo "Redirecting existing linked file $CURRENT_LINK, ${PWD}/${WRK_DIR}/${DEST_FILE}"
  exit 1
fi
