name: CI

on:
  pull_request:
    paths:
      - 'source/**'
      - 'sdk/**'
      - 'buildtools/**'
      - '.github/workflows/**'
  push:
    paths:
      - 'source/**'
      - 'sdk/**'
      - 'buildtools/**'
      - '.github/workflows/**'
    branches:
      - 'v**'
    tags:
      - 'v**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y binutils gcc make curl
          
          curl -Lo sdcc.tar.bz2 https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.2.0/sdcc-4.2.0-amd64-unknown-linux2.5.tar.bz2/download
          mkdir sdcc
          cd sdcc
          tar xjf ../sdcc.tar.bz2
          sudo cp -r sdcc-4.2.0/* /usr/local/
          sdcc -v
      - name: Install Nestor80
        env:
          N80_VERSION: '1.3.5'
          LK80_TAG: 'n80-v1.3.3-lk80-v1.1'
          LK80_VERSION: '1.1.0'
          LB80_VERSION: '1.0'
        run: |
          curl -Lo n80.zip https://github.com/Konamiman/Nestor80/releases/download/n80-v${N80_VERSION}/N80_${N80_VERSION}_SelfContained_linux-x64.zip
          unzip n80.zip
          sudo install -v N80 /usr/local/bin
          rm N80
          rm n80.zip

          curl -Lo lk80.zip https://github.com/Konamiman/Nestor80/releases/download/${LK80_TAG}/LK80_${LK80_VERSION}_SelfContained_linux-x64.zip
          unzip lk80.zip
          sudo install -v LK80 /usr/local/bin
          rm LK80
          rm lk80.zip

          curl -Lo lb80.zip https://github.com/Konamiman/Nestor80/releases/download/lb80-v${LB80_VERSION}/LB80_${LB80_VERSION}_SelfContained_linux-x64.zip
          unzip lb80.zip
          sudo install -v LB80 /usr/local/bin
          rm LB80
          rm lb80.zip
      - name: Build and install mknexrom
        run: |
          gcc -O2 -o mknexrom buildtools/sources/mknexrom.c
          sudo install -v mknexrom /usr/local/bin
          rm mknexrom
      - name: Make all
        run: make -C source
      - name: Verify sdk/nextor-kernel-version.txt is in sync
        run: |
          rm -f sdk/nextor-kernel-version.txt
          make -C source/kernel ../../sdk/nextor-kernel-version.txt
          git diff --exit-code -- sdk/nextor-kernel-version.txt
